### ISSUE TITLE
Closing the same connection multiple times leads to IllegalOperationError

### ISSUE THREAD

**Issue by xaka** [squaremo/amqp.node#111]
I think it should be totally legal to call `close` method on connection as many times as you want otherwise you end up with:

```
../node_modules/amqplib/lib/connection.js:348
    throw new IllegalOperationError(msg, stack);
          ^
IllegalOperationError: Connection closed
    at Connection.<anonymous> (../node_modules/amqplib/lib/connection.js:348:11)
    at Connection.C.closeBecause (../node_modules/amqplib/lib/connection.js:321:8)
    at Connection.C.close (../node_modules/amqplib/lib/connection.js:314:8)
    at ChannelModel.CM.close (../node_modules/amqplib/lib/channel_model.js:33:19)
    at close (../proxer/src/di/smppSessionProxerFactory.js:245:24)
    at Session.handleSmppClose (../proxer/src/di/smppSessionProxerFactory.js:184:7)
    at Session.emit (events.js:117:20)
    at Socket.<anonymous> (../node_modules/smpp/lib/smpp.js:29:8)
    at Socket.emit (events.js:117:20)
```

For instance if you have multiple TCP/IP connections to different services and one of those is being closed, you want to safety close the others in any order, and it's lame to track "closed" state of each connection manually to make sure you don't do closing more than once.

If `close` has been called already and in progress (or finished), just do nothing for next calls and add passed callback to queue.

**Comment by squaremo** [comment]
I tend towards thinking that keeping track of this state is the application's responsibility; or to put it another way, if some code calls `close` more than once, the code is incorrect.

But I think your example may be a good counter-argument: you have a number of things that depend on a common AMQP connection, and you want to be able to shut them down in any order (right?). The usual solution to this situation is to topologically sort by dependency, which effectively means shutting down all the things depending on the AMQP connection, then the AMQP connection. Being practical though, if you aren't using some kind of "component" scaffolding that will do this for you, it would be a pain to do it yourself.

If there was a `isClosingOrClosed()` method, you could ask if before attempting to close a connection. I prefer this to making `close()` idempotent, since the latter will mask genuine problems with application code. What do you think?

**Comment by richzw** [comment]
hi @squaremo

I meet one same exception here. 

```
c:\share\node\node_modules\amqplib\lib\channel.js:144
    throw new IllegalOperationError(msg, stack);
          ^
IllegalOperationError: Channel closed
    at ConfirmChannel.<anonymous> (c:\share\node\node_modules\amqplib\lib\channe
l.js:144:11)
    at ConfirmChannel.C.publish (c:\share\node\node_modules\amqplib\lib\channel_
model.js:154:15)
    at ConfirmChannel.CC.publish (c:\share\node\node_modules\amqplib\lib\channel
_model.js:296:20)
    at Sender.publish_ (c:\share\node\sender.js:146:28)
    at Sender.deliverMessage (c:\share\node\sender.js:165:20)
```

I want to if there is one method is to check whether the current channel is valid or not? or is there any event can be listened about this exception?

**Comment by nfantone** [comment]
+1 on this.

Someone at `seneca-amqp-transport` has bring this issue to us, [here](https://github.com/disintegrator/seneca-amqp-transport/issues/16).

Like the idea on `isClosingOrClosed()` API. Any updates on this?

**Comment by drwharris** [comment]
Sorry to dredge up an old issue but I'd love to see the feature mentioned previously implemented. The scenario I have just come across is where between receiving and ack/nacking a message the underlying connection is closed and reopened any attempt to ack/nack on the channel throws an exception.

The ability to check the channel status would be fantastic here.

**Comment by pramodtv** [comment]
+1
