### ISSUE TITLE
How to use the assertExchange callback with the callback_api

### ISSUE THREAD

**Issue by joaquimserafim** [squaremo/amqp.node#126]
Hey,

I'm using the callback_api and I Am testing the `assertExchange` callback (for code coverage)
in the case pass `null` as `enchange` name was not supposed to send a `error` in the `assertExchange` callback instead of throwing an error?

for example:
```
var amqplib = require('amqplib/callback_api');

var args = process.argv.slice(2);
var key = (args.length > 0) ? args[0] : 'info';
var message = args.slice(1).join(' ') || 'Hello World!';

function bail(err, conn) {
  console.error(err);
  //if (conn) conn.close(function() { process.exit(1); });
}

function on_connect(err, conn) {
  if (err !== null) return bail(err);

  var ex = undefined; 
  var exopts = {durable: false};

  conn.createChannel(function(err, ch) {
    ch.assertExchange(ex, 'topic', exopts, function(err, ok) {
      if (err !== null) return bail(err, conn);
      ch.publish(ex, key, new Buffer(message));
      console.log(" [x] Sent %s:'%s'", key, message);
      ch.close(function() { conn.close(); });
    });
  });
}
amqplib.connect(on_connect);
```

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Missing value for mandatory field 'exchange'
    at encodeExchangeDeclare (/vagrant/amqpjs/vm/test/node_modules/amqplib/lib/defs.js:873:29)
    at module.exports.encodeMethod (/vagrant/amqpjs/vm/test/node_modules/amqplib/lib/defs.js:3405:12)
    at Connection.C.sendMethod (/vagrant/amqpjs/vm/test/node_modules/amqplib/lib/connection.js:517:15)
    at Channel.C.sendImmediately (/vagrant/amqpjs/vm/test/node_modules/amqplib/lib/channel.js:59:26)
    at Channel.C.sendOrEnqueue (/vagrant/amqpjs/vm/test/node_modules/amqplib/lib/channel.js:70:10)
    at Channel.C._rpc (/vagrant/amqpjs/vm/test/node_modules/amqplib/lib/channel.js:126:8)
    at Channel.assertExchange (/vagrant/amqpjs/vm/test/node_modules/amqplib/lib/callback_model.js:140:8)
    at /vagrant/amqpjs/vm/test/index.js:44:8
    at /vagrant/amqpjs/vm/test/node_modules/amqplib/lib/callback_model.js:53:29
    at /vagrant/amqpjs/vm/test/node_modules/amqplib/lib/callback_model.js:67:7
```

what is supposed to come in the `err`?

thanks in advance

**Comment by squaremo** [comment]
Hi there,

Yes, I let "type" errors of this kind explode the whole process. I could put checks on the arguments, but I would be inclined to make them assertions, which would be not much different.

My reasoning is that invoking the callback with an error is for the situation in which the library failed to do what you asked it, rather than the situation in which code is wrong.

**Comment by daixtrose** [comment]
I tend to disagree and kindly ask to reopen this. I prefer not to distinguish between type of errors that can be caught or some which are burning the house down. Or can you help me to catch that kind of error anyway? Ths code here ends with an uncaught exception and I do not know how to fix it:

```javascript
        let connectionObservable =
            Rx.Observable.fromPromise(() => {
                return amqp.connect(_url);
            }).do(
                (conn) => {
                    console.log("Connection established!");
                    // store connection for future reference (cleanup)
                    _connection = conn;
                });

        let channel = connectionObservable
            .selectMany((conn, idx, obs) => {
                return Rx.Observable.fromPromise(conn.createChannel());
            })
            .do((ch) => {
                // store channel for future reference (cleanup)
                _channel = ch;
            })
            .selectMany((ch, idx, obs) => {
                return Rx.Observable.fromPromise(() => {
                    // establish a topic exchange connection
                    
                    // THIS TRY CATCH DOES NOT HELP, BUT WHAT DOES?
                    try
                    {
                       // ADDED WRONG ARG 'TOPICC' TO PROVOKE ERROR
                        var ok = ch.assertExchange(_exchange, 'topicc', { durable: true });
                        return ok.then(() => {
                            return ch;
                        })
                        .catch(function (e) {
                            console.log(e); // "oh, no!"    
                        });
                    }
                    catch (ex)
                    {
                        return Promise.reject(ex.message);
                    }    
                })
            });
```

**Comment by squaremo** [comment]
@daixtrose My argument above, paraphrased, is that misspelling the kind of exchange *should* end up being an uncaught exception. It's a problem with the code, not a problem with the running program.

If it were a type-checked language, you'd expect it to fail to compile. Since JavaScript is not, though, an assertion or runtime exception has to suffice.

To put it another way: what would you do if you *could* catch the exception? That part of the program will never succeed, so if there's an alternative then you should just be doing that alternative.

**Comment by daixtrose** [comment]
@squaremo IMHO misspelling should end in a catchable exception. What hapens with an errro in an URI? Same game. I would prefer to catch **any** error and deal with it appropriately. Uncaught exceptions are a nightmare for a production system and will force me to either rewrite amqplib or to switch to another implementation. Unnecessary hassle I believe.  

The problem is even bigger: I tested the lib with disabling WiFi on the client after a minute or so (cutting the network connection). Unfortunately I also obtained uncaught exceptions in this case. This means that either I made a mistake or the library emits exceptions on a side path which I cannot accept: I am in a situation where network errors are daily business (connected drive) and I want to run a reconnect trampoline and my own reconnection strategy (including round robin on servers).

So please give us a chance to at least register an error handler for these situations.

**Comment by squaremo** [comment]
If you want to handle the error that results from misspelling the exchange type, install an `'error'` handler on the connection. It's the server that know what kinds of exchanges are possible, so the library has to do an RPC; and the penalty for getting it wrong is a connection error.

If you want to handle the error that results from passing the wrong kind of value to a method, a `try..catch` will work. If it doesn't, it's probably like the above case, or I've failed to be defensive enough in looking at arguments.

**Comment by daixtrose** [comment]
> If you want to handle the error that results from misspelling the exchange type, install an 'error' handler on the connection.

Wait, I thought that a promise always emits its error. Isn't that the case? In code: I thought the following would be sufficient:

```javascript
amqp.connect(connectionUrl)
    .then(function (conn) {
        
        var ch = conn.createChannel();
        return ch;
    })
    .then(function (ch) {
        var ok = ch.assertExchange(exchange, 'topic', { durable: false });
        return ok.then(function () {
            return ch;
        });
    })
    .then(function (ch) {
        ch.publish(exchange, key, new Buffer(message));
        console.log(" [x] Sent %s:'%s'", key, message);
    })
    .catch(function (err) {
        // ====> I EXPECTED ALL ERRORS TO PASS HERE!!! <====
    	error_occured = true;
        console.log("ERROR: ", err.message);
    })
    .finally(function () {
        // ....
    });
```

Do I have to register extra error handlers? If yes, please show some code.

**Comment by daixtrose** [comment]
What should happen, if the connection URL is invalid? 
- URL could have a typo leading to invaild syntax
- syntax ok, but server could be down
