### ISSUE TITLE
How to check state of the channel?

### ISSUE THREAD

**Issue by PritamUpadhyay** [squaremo/amqp.node#157]
How can I Check whether the channel (inside any connection) is closed or open?.
I am distributing connections into channels. and when the maximum number of channels reached (let's say 1000 channels per connections), I am creating new connection.
Now at the time of disconnect, what I want to do is: I want to check how many channels from specific connection is opened/closes. If there is not any opened channel in connection, I will close that connection. Now problem is that, I am not able to figure out how to check that state of the channel from specific connection.
 Can any has any idea about this?
Thanks,
Pritam Upadhyay.

**Comment by squaremo** [comment]
Hi Pritam,

There is no straight-forward indication of whether a channel is open or closed, excepting that you get told when a channel closes (and can do the accounting yourself). This isn't because it's the wrong way to do things, just because I did not anticipate this kind of use.

So, you would have to build it for yourself at the minute. Since you are already keeping track of the channels you open, you could also add a 'closed' event handler for each to decrement the number, and check at that point if there are still any open for a connection. How does that sound?

**Comment by PritamUpadhyay** [comment]
Hi, @squaremo,

That sounds good. I will try..

Thanks,
Pritam Upadhyay.
