### ISSUE TITLE
Cancel consumer and wait for current message to be acknowledged

### ISSUE THREAD

**Issue by acroca** [squaremo/amqp.node#172]
I'm running into issues stopping my workers gracefully.
When I restart them, I want to send a `cancel` to each of the consumers using their `consumerTag` to stop getting messages, then wait for the current message to be acknowledged and then close the channel and the connection.

Is there any way to wait for the current message to be acknowledged?

In the docs it says `If the consumer is cancelled by RabbitMQ, the message callback will be invoked with null.`, but that's not happening to me. I guess it's only when the cancel is triggered from Rabbitmq, like deleting the queue.

Thanks in advance.

**Comment by jgato** [comment]
I am using this to detect if the queue has been deleted, and it worked. So "basic.cancel" is used for that (or similar unexpected unavailable queue). I think this is not the problem you are trying to solve.

**Comment by squaremo** [comment]
> In the docs it says If the consumer is cancelled by RabbitMQ, the message callback will be invoked with null.

Right -- that's if the _server_ cancels the consumer, not if you cancel it.

If _you_ cancel a consumer, you'll know it's done when you get the reply (the promise succeeds, or the callback you supplied is called).

> Is there any way to wait for the current message to be acknowledged?

Since you're doing the acknowledging, yes :) But you don't necessarily have to -- any unacknowledged messages at the time the channel closes will be returned to the queue.

**Comment by acroca** [comment]
Ok, thanks for the answer.

**Comment by squaremo** [comment]
@acroca Let me know if you got to a solution -- feel free to keep asking here if not!

**Comment by acroca** [comment]
Well, I already implemented it on my own as you suggest, I was just wondering if there was a less-manual way to do it.
