### ISSUE TITLE
TypeError: Cannot read property 'fields' of null

### ISSUE THREAD

**Issue by grahamjenson** [squaremo/amqp.node#176]
On an `connection.on("error", function(error) ...` listener I am very occasionally getting a `TypeError: Cannot read property 'fields' of null`

I am not sure why this happens, I am adding more logging to try get a the stack trace, it probably breaking about 1 every few million messages, so not a critical bug, just annoying.

**Comment by squaremo** [comment]
I wonder if it's a consumer getting a `null` -- this happens when RabbitMQ cancels the consumer (http://www.rabbitmq.com/consumer-cancel.html). Well, we shall see -- let me know when the logging turns something up. Thanks!

**Comment by pmclean1964** [comment]
I'm getting the same thing in the debug window - cannot read property "close" of null

**Comment by darthchudi** [comment]
This occurs because your consumer function is called with a null `message` when the queue which it consumes is either deleted or in a cluster scenario, the node on which the queue is located is failing/failed, which will cause the consumption to be cancelled. Basically if your consumer is cancelled by RabbitMQ (i.e the server), the message callback will be invoked with null. 

So within the consumer function/callback, a check for if the message is null can be used to detect if the queue was either deleted or if the consumer was cancelled. 

I however noticed that if I define a `connection.on('error')` handler, the consumer function/callback does not get invoked when the consumer is cancelled.  

The [RabbitMQ Consumer Cancel docs](https://www.rabbitmq.com/consumer-cancel.html) was a good pointer as well as this similar [Github issue](https://github.com/squaremo/amqp.node/issues/172)

**Comment by Uzlopak** [comment]
@squaremo 

You could actually close this issue.

**Comment by grahamjenson** [comment]
I am closing this issue, because I no longer use rabbitmq. I am not sure if this has been fixed however.
