### ISSUE TITLE
Question: Why do I need to publish twice to see my message?

### ISSUE THREAD

**Issue by kiwans** [squaremo/amqp.node#218]
I'm really not all too familiar with rabbitmq or how it works, but I'm having to create a tool that can send and receive messages, so please forgive my ignorance :)

Here's the snippet of code in which I use the callback api's publish method:

``` javascript
publishMessage: function(msg, exchange, routingKey){
    var encrypted = this.encryptMessage(msg);
    var buffer = new Buffer(encrypted,'base64');

    return this.channel.publish(exchange, routingKey, buffer);
}
```

When using this, publish always returns true. However, the part of my code that consumes messages will only receive the message every other time I publish.

Do messages only get sent out after something else happens? It almost feels like the first one gets put on a stack of some sort and only sent when another message is put on a stack afterwards.

Any help is greatly appreciated :)

**Comment by squaremo** [comment]
There's nothing tricky that this library is doing, I assure you :)

I would have a look at RabbitMQ's management console (http://www.rabbitmq.com/management.html) while you're running the code. Do the messages reach the exchange? Do they reach the queue you expect them to? Are you acknowledging them?

**Comment by anthonylebrun** [comment]
I seem to be having the same issue, maybe this is a common gotcha?

**Comment by cressie176** [comment]
Whenever I've seen this it's because I've done something stupid - like bound a second subscriber that competes for messages from the same queue. The easiest way to debug is to create a test queue via the RabbitMQ web ui, and listen to all messages. It's worth setting the max message limit to something small in case you forget to delete it afterwards.

Another alternative is to listen for 'success' and 'return' events when publishing the message. 'success' tells you the message was published, 'return' means that even though the message was published it wasn't routed anywhere.

It's a while since I read the docs, but suspect 'success' might require a confirm channel and 'return' may need the mandatory flag set, but I'm not sure. Search for "events" in the [channel api](http://www.squaremobius.net/amqp.node/channel_api.html) for more info.

**Comment by anthonylebrun** [comment]
@cressie176 @kiwans That's exactly what happened. I was using a topic queue and had (inadvertently) assigned two consumers to it. I guess the default behavior in that situation is to deliver messages in a round robin fashion to consumers. Whoops!

**Comment by marwan-tanager** [comment]
Have encountered the same issue, and it turned out there was two consumers consuming from the same queue I was publishing to. :+1: to @cressie176 for the insights.
