### ISSUE TITLE
Return promise for sendToQueue

### ISSUE THREAD

**Issue by satazor** [squaremo/amqp.node#225]
Hi @squaremo!

From the documentation:

> A confirm channel has the same methods as a regular channel, except that #publish and #sendToQueue accept a callback as an additional argument:

Is it possible to return a promise if we are using the promise based API? It feels cumbersome for the end user to mix callbacks with promises for this particular case.

Also:

> In practice this means the options argument must be supplied, at least as an empty object.

I think we can do a typeof check to allow the options object to be completely omitted.

Thoughts?

**Comment by satazor** [comment]
@squaremo another completely unrelated question to the above but I didn't want to open another issue.

The `ack()` method and friends do not return a promise nor support a callback. How does one know that the ack was successfully?

**Comment by massimocode** [comment]
@satazor I had the same question. See https://github.com/squaremo/amqp.node/issues/167 for ack/nack. Also see this commit's message for sendToQueue: https://github.com/squaremo/amqp.node/commit/7a719065eb75ec5fd2b28719b2111b0067769c08

**Comment by squaremo** [comment]
> Is it possible to return a promise if we are using the promise based API? It feels cumbersome for the end user to mix callbacks with promises for this particular case.

Yes it is, a bit; unfortunately there is no good choice here, because if the return value is a promise, there's no way to communicate backpressure (the boolean return value).

> How does one know that the ack was successfully?

You don't get the acked message back again.

You could think of it like this: an ack is there to safeguard against lost messages -- if you want a message to arrive, and it might have got lost, you can resend it; but if you send a message and get an ack for it, you don't need to send the message again. It's been taken care of. But what if the ack gets lost? Well, you could have an ack of the ack, but .. what if that gets lost? Doing any more is a waste, because, ultimately, you're going to end up resending _something_. So you may as well have few acks and just deduplicate messages.

(AMQP, and therefore RabbitMQ, and therefore this library, fall slightly short -- just having an ack, with no windowing, is not _quite_ enough to do "perfect" deduplication at the receiver. I don't think.)

**Comment by satazor** [comment]
Understood, thanks for the explanations!
