### ISSUE TITLE
No existing functionality to pass in query params in url object

### ISSUE THREAD

**Issue by JasonTowner** [squaremo/amqp.node#229]
amqp support query string params to allow further options on the connection. They are only available with `amqplib` if your param type is a url connection string; if you pass in an object, there is no support for the query string as an object.
### Missing functionality

`frameMax`
`channelMax`
`heartbeat`
`locale`

**Comment by ikhemissi** [comment]
Hi,

I added an other PR for the same issue, but the difference is that the extra configuration (e.g. heartbeat) is expected in the `url` param of `connect` instead of `socketOptions`: https://github.com/ikhemissi/amqp.node/blob/bb1e6c8efd6ec2d4598512cdedb793527f764b47/lib/connect.js#L90

I'm happy with whichever PR (#226 or #304) gets merged first, and I'm also happy to make any changes in the #304 to make it follow any contribution guidelines or roadmap goals.

Thanks guys
