### ISSUE TITLE
How does ack work?

### ISSUE THREAD

**Issue by JulianXin** [squaremo/amqp.node#293]
HI,
      I have one queue with two messages( for example msg1,msg2 ), and just one consumer for it. When the consumer got msg1 , it noack(msg1) for some other conditions not reached. Then the sonsumer got the msg1  immediately，and then noack(msg1) before the other conditions reached. So i can't consume the msg2?
     I know that add a consumer will work. But no other ways to solve this?

**Comment by cressie176** [comment]
When you nack a message it's put back to the front of the queue, and will therefore be picked up again almost immediately. As you mention one option is to add a second consumer. Another is to increase the prefetch so you one consumer will get multiple messages from the queue.

However neither of these options are likely to be appropriate for two reasons.

1. Rabbitmq is so fast you can easily end up replaying the nacked message thousands of times a second, sending your CPU through the roof and generating a tonne of logging (assuming you use logging)

2. If a second duff message arrives you're back in the same situation.

Alternative options which may or may not be appropriate are...

1. Setup a dead letter exchange so when you nack the message it is routed to the dead letter queue instead of being replayed. This leads to the question of what you do with it now it's on a dead letter queue? One popular option is to set a ttl on the dead letter queue. When the ttl expires the message will be automatically nacked by rabbit. By configuring the dead letter queue with it's own dead letter exchange it can be routed back to the original queue after a short period of time, i.e. you have delayed retry. See [here](https://gagnechris.wordpress.com/2015/09/19/easy-retries-with-rabbitmq/) for a more thorough explanation.

If the above is too much configuration, other (hacky) options are...

1. Add a consumer / increase the prefetch and delay the nack using setTimeout. Not great, because it's still possible to block your consumers when you get more duff messages, but better than thrashing the CPU

1. Instead of nacking the message resend it to the same queue then nack without requeue. This has the effect of putting the message to the back of a queue, giving other messages the option of being consumed, however if your channel is lost (e.g. due to application shutdown) between resending and nacking you'll create a duplicate message, so you'll need to make sure your application can cope with this.

**A word of warning**
None of the above solutions will help if instead of nacking your message, there's something unexpected in it which causes your app to crash. Under this circumstance the message will always be rolled back. If your application has multiple consumers the same "poison" message will crash them all in quick succession. If your application automatically restarts it will keep crashing it rapidly until you somehow remove the "poison" message from the queue. Rabbit does give you the option of checking if a message has been redelivered, but doesn't provide a way of counting the number of redeliveries. The best solution I've come up with for resolving this is to ensure each message has a unique id, and to maintain an external count (e.g. in redis) of redelivered messages. When the external count hits a threshold I log it, then immediately nack it without requeue, meaning the message is lost (but it was poisoned anyway).

**Comment by squaremo** [comment]
Wow that is a great answer @cressie176!

**Comment by squaremo** [comment]
@JulianXin I'm closing this as you seem satisfied with Stephen's answer; but if you still need advice, please reopen this or create a new issue.
