### ISSUE TITLE
autoDelete not work

### ISSUE THREAD

**Issue by cage1618** [squaremo/amqp.node#306]
I set option `autoDelete` as true for a queue, but sometime even if consumer is 0, the queue still exist How can I find the reason? thanks

![image](https://cloud.githubusercontent.com/assets/2541448/20258563/2b340c58-aa8b-11e6-809c-3bdb6d4f0c00.png)

**Comment by cressie176** [comment]
The following extract from the [RabbitMQ docs](https://www.rabbitmq.com/amqp-0-9-1-reference.html) might explain it...

**auto-delete**
If set, the queue is deleted when all consumers have finished using it. The last consumer can be cancelled either explicitly or because its channel is closed. If there was no consumer ever on the queue, it won't be deleted. Applications can explicitly delete auto-delete queues using the Delete method as normal.

The server MUST ignore the auto-delete field if the queue already exists.

**Comment by cage1618** [comment]
thanks a lot

**Comment by squaremo** [comment]
@cage1618 Can this be closed?

**Comment by cage1618** [comment]
@squaremo yes, thanks very much!

**Comment by KrupanKasam** [comment]
@cage1618....please..,send notes regarding how you fix this issue now i have same problem....

**Comment by cage1618** [comment]
@KrupanKasam sorry，just saw the message。

You can use `channel.checkQueue(queueName)`, it will return `consumerCount` when queue exist and throw an error when queue doest't exist.

when consumerCount is 0, I call `channel.purgeQueue` to clear all message and call `channel.deleteQueue` with ifUnused = true and ifEmpty = true to delete the queue.
