### ISSUE TITLE
ch.CANCEL don't work

### ISSUE THREAD

**Issue by eluizbr** [squaremo/amqp.node#308]
Hi,

I'm try use de ch.cancel, and don't have success. I'm try send this:

```
    amqp
        .then(conn => {
            return conn.createChannel();                
        })
        .then(ch => {
            ch.cancel('amq.ctag-5god15Y763oixUs2Uv2aAA', (err, ok) => {
                console.log(err, ok);
            });
        });
```
Nothing happen. I try cancel an queue with contain 300K.
Don't receive any error or ok in console.log.

Any tips?

Thanks.

**Comment by michaelklishin** [comment]
What exactly do you expect to happen?

Cancelling a consumer that does not exist (it doesn't in the snippet above it) is a channel-level error.
Queues are not cancelled, they can be deleted. Consumers can be cancelled but that does not delete the queue *unless the queue is auto-deleted*.

**Comment by squaremo** [comment]
JS syntax and promise support vary between versions, but in any case this looks a lot like you are mixing the promise and callback APIs. In the call to cancel you supply a callback, but I suspect you need to treat it as returning a promise.

**Comment by eluizbr** [comment]
@michaelklishin, i expect send an PAUSE to the queue. This is possible ?
Thanks.

**Comment by michaelklishin** [comment]
@eluizbr cancelling a consumer will stop all new deliveries but there can still be some in flight.

Your issue is a little light on the details about what you're doing, what your expectations are and what you observe. If I was investigating this I'd check server logs to make sure you don't attempt to use an unknown consumer tag and then see consumers table in the management UI for the queue in question.

**Comment by eluizbr** [comment]
I'm already do this.. The TAG is correct.
My idea is give on user the power the STOP and START your jobs.
Thanks.
