### ISSUE TITLE
nack with updated header properties

### ISSUE THREAD

**Issue by Drjonees** [squaremo/amqp.node#325]
Hi!

I'm trying to implement a small delivery counter.
This is my code: 
```
let deliveryCount = Number(message.properties.headers['x-delivery-count']) || 0;
message.properties.headers['x-delivery-count'] = deliveryCount + 1;
channel.nack(message, false, true);
```

If I console.log the message after the +1, I see that the header property is updated.
But when I receive the message afterwards the counter is back to it's original value.

Can I not update the message and send it back into the queue with nack?

**Comment by michaelklishin** [comment]
No, you can't. `basic.ack` and `basic.nack` only carry a delivery tag and a bunch of other options but not message payloads or any other attributes. Messages cannot be modified by clients between redeliveries as far as messaging protocols go and it's a very good thing.

**Comment by Drjonees** [comment]
Okay thank you.

I tried another approach.
Nack the message and then publish a new one with the updated counter.

The problem is that the nack'ed message will be put in the dead letter queue and the new message will have different ID's. 

How can i achive the counter?

**Comment by cressie176** [comment]
With what you're describing you could ack the message instead of nacking it. However you need to be careful...

1. Acking the message before publishing the decorated one will lead to lost messages if your application crashes / is shutdown between acking and publishing
2. Acking the message after publishing the decorated one will lead to duplicate messages if your application crashes / is shutdown between publishing and acking.

You have to pick which of these two evils are acceptable in your situation. Another approach is to store the counter externally to the message (e.g. in Redis)

Can you decorate each message with a message Id when you publish it, then increment the redis counter using the message Id if you see it again?

If your purpose is to count redeliveries you can use the boolean "redelivered" header to make things more efficient

```
if (headers.redelivered) {
   redis.incAndGet(message.headers.id, (err, count) => {
     if (err) return console.error(err)
     if (count > 10) return deadLetter(message)
     processMessage(message)
   })
}
```

See https://github.com/guidesmiths/rascal#dealing-with-redeliveries for how I handle this with Rascal.

**Comment by Drjonees** [comment]
Thank you!

So I have 3 different evils to pick from. Awesome ;-)
