### ISSUE TITLE
Creating an HTTP gateway using amqplib

### ISSUE THREAD

**Issue by nareshbhatia** [squaremo/amqp.node#341]
I am trying to create an API gateway that will receive HTTP requests and respond with information collected from RabbitMQ. I would like to use the RPC approach described [here](https://www.rabbitmq.com/tutorials/tutorial-six-javascript.html). I am not sure how to adapt the last example on this page to structure my gateway code - mainly because the response is nested inside the callback supplied to `channel.consume()`. Ideally, I would like to structure my code as a function that takes some request parameters and returns a promise that contains the response. For example:

```
getAccount(accountId) {
    // return a promise that resolves to an account object
}
```

How do I achieve this with the amqplib API?

Thanks in advance.

**Comment by nareshbhatia** [comment]
Not sure if this is the right place to ask this question. Please advise.

**Comment by cressie176** [comment]
Hi @nareshbhatia. I think the question is a bit broad. Your best best is to get familiar with amqplib and ask specific questions about the API as you encounter them rather than "how do I design my app" type questions.

Having said that I did play with an [http to amqp bridge](https://github.com/guidesmiths/httq) you might find useful. It was more of a prototype than anything I used in production, but might provide useful. All it does is allow you to POST messages to RabbitMQ by converting the URL into a routing key.

You might also want to take a look at [stashback](https://github.com/guidesmiths/stashback).

Neither use promises because I'm a grumpy old git who thinks they suck ;)

**Comment by nareshbhatia** [comment]
@cressie176 thanks for helping out.

- I don't know rascal, so understanding httq may take some time. However from your description, it seems that httq does not do RPC. In other words, it does not to wait for a message response and send it back as an HTTP response. Is this understanding correct?

- stashback is much simpler to understand and looks like it does exactly what I am looking for. One question though - in the code in README.md - `onMessage()` looks like a hanging function. I can't figure out where it is wired or how it gets called. Can you please clarify?

**Comment by cressie176** [comment]
`onMessage` would need to bound to your RabbitMQ subscriber. When you get the reply, call onMessage, which will unstash the callback and respond to the http request. There's an [example](https://github.com/guidesmiths/stashback/tree/master/example) folder that might make it clearer.

**Comment by nareshbhatia** [comment]
Thanks @cressie176, the example makes it clear. I will give stashback a try. Will post any followup questions on that project. Thanks again for your help.
