### ISSUE TITLE
Using waitForConfirms()

### ISSUE THREAD

**Issue by dland512** [squaremo/amqp.node#375]
I'm a little unsure about the best way to ensure that all messages have reached the queue before closing a channel. If you make use of the callback in `sendToQueue()` do you also have to call `waitForConfirms()`? Take this code for example:

```
function sendStuffToQueue(messages) {
    conn.createConfirmChannel()
        .then((channel) => {
            let promises = [];

            for (let message of messages) {
                promises.push(createPromise(channel, 'MyQueue', message));
            }

            Promise.all(promises)
                .then(() => {
                    return channel.waitForConfirms();
                })
                .then(() => {
                    return channel.close();
                });
        });
}

function createPromise(channel, queue, message) {
    return new Promise((resolve, reject) => {
        channel.assertQueue(queue)
            .then(() => {
                channel.sendToQueue(queue, msg, {}, (err) => {
                    if(err)
                       reject(err);
                    else
                       resolve();
                });
            });
    });
}
```

So here, due to how `Promise.all()` works, `channel.waitForConfirms()` will not execute until all the callbacks for `sendToQueue()` have executed. So is there any point in calling `channel.waitForConfirms()` at that point?

Or, alternatively, since I'm not really doing anything with the callback values, could I just not provide the callback when calling `sendToQueue()` and use `waitForConfirms()` to know when its okay to close the channel? Like this:

```
function sendStuffToQueue(messages) {
    conn.createConfirmChannel()
        .then((channel) => {
            let promises = [];

            for (let message of messages) {
                promises.push(createPromise(channel, 'MyQueue', message));
            }

            Promise.all(promises)
                .then(() => {
                    return channel.waitForConfirms();
                })
                .then(() => {
                    return channel.close();
                });
        });
}

function createPromise(channel, queue, message) {
    return new Promise((resolve, reject) => {
        channel.assertQueue(queue)
            .then(() => {
                channel.sendToQueue(queue, msg);
                resolve();
            });
    });
}
```

**Comment by squaremo** [comment]
You got it -- either providing a callback, _or_ using `waitForConfirms`, is sufficient. Gathering up callbacks and using `Promise.all` is essentially replicating the work `waitForConfirms` does, so you may as well just use the latter.

A small nit with your example: you're asserting the queue before sending each message, which means a extra round-trip. I'd assert the queue on entry to `sendStuffToQueue`, or even just once right at the start.

**Comment by dland512** [comment]
I see, so you don't need `Promise.all()` and `waitForConfirms()`. So basically the code could be this:

```
function sendStuffToQueue(messages) {
    let channel;

    conn.createConfirmChannel()
        .then((ch) => {
            channel = ch;
            return channel.assertQueue(queue);
        })
        .then(() => {
            for (let message of messages) {
                channel.sendToQueue(queue, msg);
            }
            
            channel.waitForConfirms()
                .then(() => {
                    channel.close();
                });
        });
}
```

That makes sense. However, I don't think I can use that specific pattern because the message determines which queue to insert into. I kept that fact out of the original example to keep it simple, but the real code looks more like this:

```
sendStuffToQueue(messages) {
    return this.conn.createConfirmChannel()
        .then((channel) => {
            let promises = [];

            for (let message of messages) {
                let queue = message.category;
                promises.push(this.send(channel, queue, message));
            }

            Promise.all(promises)
                .then(() => {
                    channel.waitForConfirms();
                })
                .then(() => {
                    return channel.close();
                });
        });
}


send(channel, queue, message) {
    return new Promise((resolve, reject) => {
        channel.assertQueue(queue)
            .then(() => {
                let msg = Buffer.from(JSON.stringify(message));
                channel.sendToQueue(queue, msg);
                resolve();
            });
    });
}

```

Quite a bit more complicated unfortunately, but because I have to call `assertQueue` on each queue separately, this is what I ended up with.

**Comment by squaremo** [comment]
Every call to `assertQueue` and subsequent `sendToQueue` is unsafe, in the sense that anyone could delete the queue in-between those calls. Depending on what else if going on in your infrastructure, this could mean you don't have worry about it, or you always have to worry about it. There's no right way, you get to choose the level of risk you're happy with.

One thing to be aware of is that you will not in general get told if `sendToQueue` mentions a queue that doesn't exist. That's because it is implemented (per AMQP) as a routing rule, and routing to nowhere is considered a success. I _think_ you can mark a message as `mandatory` to turn that case into a rejection, but it is certainly worth reading the documentation on this (http://www.rabbitmq.com/amqp-0-9-1-reference.html#class.basic) to figure out what you want.

**Comment by dland512** [comment]
My app is the only one creating queues or inserting things into them so I think it should be fine.

Good to know about sending a message to queue that doesn't exist. Seems a bit odd that the AMQP spec would be written to indicate success in that case, but whatev. Spec writers, am I right?? As long I can rely on `assertQueue` to actually create the queue if it doesn't already exist, then it should be fine.

**Comment by cressie176** [comment]
@dland512 I just answered a question [here](https://github.com/squaremo/amqp.node/issues/405) explaining why sending a message to a missing queue doesn't fail. I agree it's counterintuitive, but there is at least some method to the madness. There's also an example of listening for the "return" event.

WRT to assertQueue - yet it will create the queue if it doesn't exist, however if fails if the queue exists but with a different configuration rather than redefining it (I don't think this is supported by RabbitMQ)
