### ISSUE TITLE
ACCESS-REFUSED after upgrade to version 0.5.2

### ISSUE THREAD

**Issue by NilsFrkal** [squaremo/amqp.node#392]
Connection to RabbitMQ works fine with 0.5.1, but after npm update to version 0.5.2 I get error "Connection error to rabbitMQ Error: Handshake terminated by server: 403 (ACCESS-REFUSED) with message "ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN." Downgraded to 0.5.1 again and everything works.

**Comment by squaremo** [comment]
Hrm, there were some changes to authentication in this release -- see #330. Is it possible that your username(s) include a colon? If so, you may need to use an object with separate username and password fields, as covered under http://www.squaremobius.net/amqp.node/channel_api.html#connect.

**Comment by cressie176** [comment]
We've also upgraded to 0.5.2 and have had one incidence of this. One of our services reconnected at 4am, and got a 403 (ACCESS-REFUSED) with message "ACCESS_REFUSED" message. The service reconnected to the next node in the cluster and everything worked fine. There's no chance the password was changed. The password only contains alpha numerics

**Comment by squaremo** [comment]
> The service reconnected to the next node in the cluster and everything worked fine.

That's a bit frightening -- I'm not sure where this kind of non-determinism would have crept in.

**Comment by cressie176** [comment]
Probably should explain the reconnect bit. We're using [Rascal](https://github.com/guidesmiths/rascal) which automatically reconnects on error. If you have Rabbit configured for HA and you specify an array of connections Rascal will randomise the array at startup, then cycle through them if it needs to reconnect. We're having some network issues at the moment, which cause heartbeat timeouts so we're erroring / reconnecting a few times a week. One of these resulted in the 403. As far as I know it hasn't happened since, but worth keeping an eye out for.

**Comment by cressie176** [comment]
Closing - I haven't seen this in a long time.
