### ISSUE TITLE
HTTP_PROXY support for amqplib?

### ISSUE THREAD

**Issue by spdaley** [squaremo/amqp.node#394]
We are currently trying to configure our node product which uses amqplib to use an http proxy. I cannot seem to find any configuration settings for using a proxy though. Is there some mechanism to configure one with it? In particular, using HTTP_PROXY/HTTPS_PROXY environment variables would be nice.

**Comment by cressie176** [comment]
Hi @spdaley,

This is not something I have any experience of but would hazard a guess that since AMQP isn't an HTTP based protocol, that layering something on top you won't be able to get it to work with an HTTP proxy.

According to the [RabbitMQ docs](https://www.rabbitmq.com/protocols.html) you can get Rabbit to use HTTP via the Web-STOMP or JSON-RPC channel plugin, but I suspect you'll need to use an alternative library such as [stompjs](https://www.npmjs.com/package/@stomp/stompjs) or [json-rpc2](https://www.npmjs.com/package/json-rpc2).

If you chose a websocket based approach you may need extra steps for configuring your proxy server, e.g. https://www.nginx.com/blog/websocket-nginx

**Comment by spdaley** [comment]
Hi @cressie176 

Thanks. That makes total sense. Luckily this isn't a huge priority for us at this time but this is good info for us to document when the time comes to fully support this. Closing this out.
