### ISSUE TITLE
Confirm message was delivered

### ISSUE THREAD

**Issue by thiagoretondar** [squaremo/amqp.node#405]
Hey there

I'm creating a service which every request from a specific endpoint must be queued in RabbitMQ. As an answer for each request, this endpoint must return a HTTP Status 200 if the message was successfully queued. If occur that the message isn't queued, the endpoint must return HTTP Status different from 200.

I'm using `createConfirmChannel`, and sending `mandatory: true` option in `sendToQueue`, but the answer for this method is always `true`, even if I configure to publish a message in a queue that doesn't exist.

Is there a way to know this information in synchronous way?

**Comment by cressie176** [comment]
You don't say whether you're publishing directly to a queue using `channel.sendToQueue` or to and exchange using `channel.publish`. It doesn't actually affect anything but I'll explain how `sendToQueue` works before going further just in case.

When you send a message directly to a queue, Rabbit actually publishes the message to a default exchange, and uses the queue name as the routing key. All queues are bound to the default exchange using their name, so 

```channel.sendToQueue('q', content)```

is identical to 

```channel.publish('', 'q', content)```

and whether you use `channel.sendToQueue` or `channel.publish` you are always publishing to an exchange. If the exchange exists (and the default exchange will always exist) then the message will be confirmed on acknowledgement even if it never actually gets routed to a queue, so

```channel.sendToQueue('missing', content)```

will confirm providing the message was successfully delivered to the default exchange. This is unhelpful in your situation, however there is a partial solution. If a message is not routed to a queue it will be "returned".

```channel.on('return', (msg) => console.log('Message was returned'))```

So you may be able to do something like

```js
const amqp = require('amqplib/callback_api');

amqp.connect('amqp://localhost', function (err, conn) {
  console.log('connected');
  conn.createConfirmChannel(function (err, ch) {
    if (err) die(err);
    ch.on('return', (msg) => {
      console.log('returned');
    });
    ch.sendToQueue('missing', new Buffer('something to do'), { mandatory: true }, (err) => {
      if (err) die(err);
      console.log('sent');
    });
    ch.waitForConfirms((err) => {
      if (err) die(err);
      console.log('confirmed');
    })
  });
});

function die(err) {
  console.error(err.message);
  process.exit(1);
}

setInterval(() => {}, 5000)
```
When I run the above I get
```
connected
returned
sent
confirmed
```
However I'm not sure of that you are guaranteed to get the return event, before the sendToQueue  callback is executed, or before the publish is confirmed so you'll have to investigate. If it is guaranteed you could record the check to see whether the message had been returned before sending your HTTP response. If it's not, you have a lot more work to do and it's worth asking whether the feature you're trying to implement actually makes sense in this architecture.

Just returning that a message was successfully published to a queue doesn't actually tell you very much. The queue might have no consumers. The consumer might be unable to process the message.  If it's important the client knows whether the message was successful they will either have to be notified on success or failure, or request/poll the status of the operation at a later date. Given this maybe your design could be changed to...

1. Generate a uuid
1. Publish message (set message id to the uuid to support debug)
1. Wait for confirms
1. Respond 202 (ACCEPTED) with uuid in the body
1. On return handle the failure in the same way you would downstream (notify the client that uuid failed, or allow them to request a status update)

If you really need to know whether your message was delivered to a queue before you respond to the client, then your other option is to have the queue consumer notify the publisher when the message has been received. The publisher will have to wait for this confirmation before responding to the client.  This is likely to be a very bad approach since it is likely to be slow, and depending on load increase the chances of client timeout or running out of http connections. Not recommended.

**Comment by thiagoretondar** [comment]
@cressie176 Got it. Thanks!

**Comment by cressie176** [comment]
Looks like when in confirm mode with mandatory set you should be ok...

https://www.rabbitmq.com/confirms.html#when-publishes-are-confirmed

**Comment by cressie176** [comment]
Also according to https://github.com/squaremo/amqp.node/issues/375 waitForConfirms is unnecessary in the above (will edit) as the callback should be sufficient

**Comment by thiagoretondar** [comment]
@cressie176 one doubt I have related with Channels.

In my scenario, my system will publish one message in RabbitMQ per Request. So my controllers opens one Channel with the connection and doesn't kill it, like is said in here: https://www.cloudamqp.com/blog/2017-12-29-part1-rabbitmq-best-practice.html

> Don’t open a channel for each time you are publishing.

But if I receive lots of requests, thousands in one seconds, let's say, I still should keep only one channel? I don't know if I open (or consume a factory of opened channel) is better. What is your considerations on that point?

**Comment by cressie176** [comment]
There are a few options regarding channels, and I would be suspicious of anyone offering advice unless they frame it with a particular context.

Most of the applications I write tend to publish only a handful of messages per minute. The messages aren't time critical, but could be worth a few thousand pounds each. Therefore it's much more important we confirm messages have been delivered, and that messages aren't lost in transit, that any performance concerns.

For this reason I initially used a single confirm channel per publisher and queued messages in memory so that they were published sequentially as I didn't want to risk a channel error taking out multiple messages. If a channel error occurs we recreate the channel automatically. If a connection error occurs we automatically reconnect to the next node in our cluster, then resume publishing messages from the in memory queue. When a message is confirmed, we respond to the client with a 202 and transaction id as previous explained.

When we publish messages we mandatory flag to true, use durable queues and ensure the messages are persisted, even though this is about the slowest combination of settings possible (especially in a HA environment).

However this approach wasn't always appropriate. Sometimes we synchronise distributed systems streaming documents from mongo, and publishing them to Rabbit. The above design was undesirably slow. To mitigate this we introduced a channel pool, so that we still have one message on a channel at a time, but can publish concurrently. With this setup we can publish thousands of messages a second.

Other systems in our estate have different requirements still. Our analytics platform captures our web events (page impressions, downloads counts, etc). Here can accept a small chance of message loss, but performance is far more critical. We multiplex publishes using a single non confirm channel and do not persist messages.

So in your circumstance, if you are genuinely likely to get thousands of requests per second, the simplest option is to keep open a confirm channel, and take advantage of the multiplex support (as per the cloudamqp article). You're unlikely to get an channel error when publishing messages that's not related to the underlying connection, and from what you said earlier you can report the failure via an HTTP response.

**Comment by alexaleluia12** [comment]
This is a good article.
Would be nice if this was mentioned on the documentation.
