### ISSUE TITLE
Liveness Check

### ISSUE THREAD

**Issue by victorherraiz** [squaremo/amqp.node#423]
Hi, 

I am implementing a health endpoint for an express application, at the moment I am using the channel checkQueue method to probe the rabbitmq endpoint.

I wonder I could use only the connection (it already has a liveness checks) to get the same result.

**Comment by squaremo** [comment]
The connection failing is an indication that the RabbitMQ server isn't available. But the connection being open is not a good indication that the server _is_ available, because heartbeats are relatively slow to detect connection problems -- you have to fail a couple of them consecutively, and they are typically O(minutes) apart. So you won't always know immediately if the server isn't available.

On the other hand, asking a question of the server and getting an answer (e.g., checkQueue) certainly does indicate liveness. So if you need an exact answer, that's better.
