### ISSUE TITLE
Arguments in options get turned into strings

### ISSUE THREAD

**Issue by aengl** [squaremo/amqp.node#448]
When trying to use a plugin that requires a boolean x-type, I noticed that my arguments get turned into strings. Code:

```
const amqp = require('amqplib');

const test = async () => {
  const connection = await amqp.connect('amqp://localhost');
  const channel = await connection.createConfirmChannel();
  await channel.assertQueue('test', {
    arguments: {
      'x-message-deduplication': true,
    },
  });

  await channel.close();
  await connection.close();
  process.exit(0);
};

test();
```

When investigating the features, the management interface shows the following:

<img width="489" alt="features" src="https://user-images.githubusercontent.com/5022924/43832047-c685e13e-9b0e-11e8-928c-530c1ad5524e.png">

**Comment by squaremo** [comment]
If I create an exchange through the RabbitMQ management UI, and give it an argument with type boolean, it also displays in the UI as being a string. When I list the exchanges along with their arguments using rabbitmqctl:

    rabbitmqctl list_exchange name arguments

the exchange I created has a boolean-looking value (it's the second one):

```
$ rabbitmqctl list_exchanges name arguments
Listing exchanges for vhost / ...
my-exchange     [{"x-delayed-type","direct"}]
foobaz  [{"x-boolean-arg",true}]
# ...
```

I suspect the management UI is getting it wrong, rather than amqplib or rabbitmq-server. Does the plugin fail to work as expected?

**Comment by aengl** [comment]
You are indeed correct, this seems to be an issue with the management UI instead. Apologies for the trouble. I had initially suspected that was why the plugin failed, but the problem ended up being something else instead.

**Comment by squaremo** [comment]
No worries! It's often difficult to diagnose from the outside what's going on. You could consider lodging an issue with https://github.com/rabbitmq/rabbitmq-management about its display of the arguments table; I had a scan and didn't see one already.
