### ISSUE TITLE
Cannot connect without network

### ISSUE THREAD

**Issue by taozi0818** [squaremo/amqp.node#449]
On Windows OS, I cannot connect the Rabbitmq server when I turn off the network.
Both my application and Rabbitmq server is running on localhost.

- Node.js Version: 8.9.3
- amqplib Version: 0.5.2
- Rabbitmq server Version: 3.7.7

My application will catch an error `getaddrinfo ENOENT` when network is broken.

It never happend on CentOS and MacOS.

**Comment by cressie176** [comment]
Maybe the windows machine isn't able to resolve the hostname of your RabbitMQ server, whereas maybe CentOS and MacOS are retrieving it from DNS cache?

- What are your connection parameters (excluding password obviously).
- What happens if you ping the host in your connection parameters from the command line.

**Comment by taozi0818** [comment]
@cressie176   I resolved. Checkout the hosts file on Windows OS, I found the hostname `localhost` has not been mapped to `127.0.0.1`. 😄
