### ISSUE TITLE
Connection Reset Error

### ISSUE THREAD

**Issue by honestserpent** [squaremo/amqp.node#455]
Hi, I am experiencing this error and I don't know how to handle it.

I have publishers that publish a bunch of messages to an exchange in a Confirm Channel. After all the publishing, there is a `waitForConfirms()`.

If I run in debug and stop on a breakpoint before the `waitForConfirms()` for a sufficient amount of time, when I go forward this error is thrown: 
```
Exception has occurred: Error
Error: write ECONNRESET
    at _errnoException (util.js:1024:11)
    at Socket._writeGeneric (net.js:770:25)
    at Socket._write (net.js:789:8)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:707:40)
    at roundrobin (c:\Users\Username\workspace\my-project\node_modules\amqplib\lib\mux.js:65:27)
    at Mux._readIncoming (c:\Users\Username\workspace\my-project\node_modules\amqplib\lib\mux.js:82:3)
    at Immediate.<anonymous> (c:\Users\Username\workspace\my-project\node_modules\amqplib\lib\mux.js:112:12)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
```

The fact that I have to wait a certain amount of time obviously makes me think to some sort of timeout, which I find ok.

What is weird to me is, though, that even if I am using `async/await` and everything is in a `try/catch` I am unable to catch the exception.

This is the code i'm running:
```javascript
[...]
try {
  for (let i = 0; i < msgs.length; i++) {
    ch.publish(exchange, 'data1.count', Buffer.from(msgs[i]), { persistent: true });
  }
  await ch.waitForConfirms();
} catch (err) {
  return next(err); // I don't go here, instead, I have an uncaught exception
};
[...]
```

**Comment by drwharris** [comment]
I have noticed the same behavior under the same conditions. Have you found a way to catch this and retry?

**Comment by cressie176** [comment]
From the [nodejs.org error docs](https://nodejs.org/api/errors.html)

> ECONNRESET (Connection reset by peer): A connection was forcibly closed by a peer. This normally results from a loss of the connection on the remote socket due to a timeout or reboot. Commonly encountered via the http and net modules.

So what is happening is that the remote side of the connection is being closed abruptly. This could be for a number of reasons (I was getting it the other day due to an unhealthy AWS instance hosting our application - we needed to reboot it in order to fix).

**Comment by cressie176** [comment]
> If I run in debug and stop on a breakpoint before the waitForConfirms() for a sufficient amount of time, when I go forward this error is thrown:

If you block or saturate your event loop, the client will be unable to send a heartbeat to the server. Under these circumstances the server will think the client has gone away and close the connection. When I simulate this using [sleep](https://www.npmjs.com/package/sleep) I get "Error: Unexpected close" rather than ECONNRESET, but maybe there's a difference between our node or amqplib versions. You could run some experiments with the heartbeat connection parameter or socket options (see the [channel api](https://www.squaremobius.net/amqp.node/channel_api.html) docs)

**Comment by cressie176** [comment]
> Have you found a way to catch this and retry?

What happens if you attach error listeners to the connection and channel objects, e.g.

```
connection.on('error', console.error);
channel.on('error', console.error);
```

**Comment by drwharris** [comment]
So in the OP's and my example, we are debugging and holding the channel(?) open for a long period of time (> 15 secs in my instance) before ack/nacking the message. 

I have connection.on('error', console.error) but it reports nothing. I will try on the channel and see what happens.

**Comment by drwharris** [comment]
So there you have it... On my connection method I had just
`				conn.on("close", async function () {
					Logger.error(`[${this.constructor.name}]: Connection Closed - Reconnecting`);
					new Promise(resolve => setTimeout(resolve, delay));
					return this._connect(this._connectionString, 60000);
				}.bind(this));`

And the app would barf if I didn't ack/nack a message in a reasonable time. The above code wouldn't get executed. 

I added

`				conn.on("error", async function (err:any) {
					Logger.error(`[${this.constructor.name}]: Connection Error - ${err}`);
				}.bind(this));`

And all of a sudden the original "On Close" code would get triggered and the app recovers.

Its odd but in the end it works, so thanks for the pointer.

**Comment by cressie176** [comment]
@drwharris apologies if you know this, but reading your "it's odd" response, I'm not clear...

In node, you must handle "error" events, otherwise they'll crash the node process. I before when you were handling just the "close" event I suspect the "error" event was firing first and crashing your application before the "close" event had a chance to be called.

@honestserpent does any of the above help with your original issue and if so, is it OK to close?

**Comment by drwharris** [comment]
@cressie176 a month into Node so that makes perfect sense now that its been explained 👍

**Comment by cressie176** [comment]
https://medium.com/dailyjs/how-to-prevent-your-node-js-process-from-crashing-5d40247b8ab2 is worth a read, to see the different types of event that can crash your application. 

However, it's generally a bad idea to catch error events to prevent the application from crashing. If you were to handle a connection error without attempting to recover, then any subscriptions would be disconnected, and your application would stop consuming messages. The same is potentially true for any library that uses persistent connections (e.g. database drivers etc).

Instead I try to

1. Attach error handlers directly to the emitter and recover where possible (e.g. by reconnecting / resubscribing)
1. Attach error handlers to `process` and attempt an orderly shutdown, and allow the process monitor (docker / kubernetes / pm2 etc) to restart.

**Comment by cressie176** [comment]
Closing. Happy to reopen if not resolved

**Comment by einsqing** [comment]
This problem is often encountered when the network environment is unstable
