### ISSUE TITLE
NACK message and immediate redelivery

### ISSUE THREAD

**Issue by honestserpent** [squaremo/amqp.node#488]
My experience: in a publish/subscribe scenario, if a subscriber nacks a message, the nacked message is immediately re-queued at the front of the queue and it will be the next message to be delivered to the subscriber.

Is there a way to avoid this? Is is possible to nack a message in a way that the next message will definetly not be the one just nacked?

**Comment by squaremo** [comment]
This is entirely down to server behaviour. The relevant RabbitMQ documentation is https://www.rabbitmq.com/nack.html. You may be able to rig something up using dead lettering -- https://www.rabbitmq.com/dlx.html.

**Comment by cressie176** [comment]
@honestserpent yes, you understood correctly.

You'll need to add the following options to the DLQ
```
x-message-ttl: TTL_IN_MILLIS
x-dead-letter-routing-key: ORIGINAL_QUEUE_NAME
x-dead-letter-exchange: SHOULD_BE_BLANK
```

When a message arrives on the DLQ it will wait for TTL_IN_MILLIS then be NACKED to the default exchange. The default exchange is automatically bound to every queue using the queue name, so by specifying this in the `x-dead-letter-routing-key` option your message will be redelivered.

Please test this out for repeated cycles before using it in production. I found the following paragraph in the [RabbMQ documentation](https://www.rabbitmq.com/dlx.html). I think everything will be OK because there will be a rejection in the cycle, but not 100% sure.

> It is possible to form a cycle of message dead-lettering. For instance, this can happen when a queue dead-letters messages to the default exchange without specifying a dead-letter routing key. Messages in such cycles (i.e. messages that reach the same queue twice) will be dropped if there was no rejections in the entire cycle.

Also please note my earlier comment about poisoned (corrupt) messages causing indefinite retry loop.
