### ISSUE TITLE
When the queue not exist, Why i can sent messages to is successfully?

### ISSUE THREAD

**Issue by yqsailor** [squaremo/amqp.node#492]
When the queue not exist, Why i can sent messages to is successfully?

**Comment by squaremo** [comment]
Because that's how AMQP works. Publishing a message does not guarantee that it is routed somewhere. If you want to be told about routing failures, use the `mandatory` flag (https://www.rabbitmq.com/amqp-0-9-1-reference.html#basic.publish.mandatory). In amqplib, unroutable messages are returned via the `'return'` event of a channel (http://www.squaremobius.net/amqp.node/channel_api.html#channel_events)

**Comment by yqsailor** [comment]
But I want know it was send to queue successfully when sending, what should I do?
