### ISSUE TITLE
How to confirm the messages was send to queue successfully?

### ISSUE THREAD

**Issue by yqsailor** [squaremo/amqp.node#493]
When send messages to queue that persistent is true, How to confirm it was send to queue successfully?

**Comment by cressie176** [comment]
Hi @yqsailor, if you search the old issues you'll find lots of discussion on this. It's also worth reading the RabbitMQ documentation on [publisher confirms](https://www.rabbitmq.com/confirms.html#publisher-confirms).

Long story short, about the only option for doing what you've asked is

1. Use a confirm channel
1. Make the message mandatory
1. Wait a short period of time to see if you get a returned message
1. If you don't get a returned message assume it was successful

The problem is in most cases waiting to see whether you get a returned message isn't a viable option. It will hurt performance, and there is still no way to guarantee you won't get a returned message after you've finished waiting.

Instead it's usually better to architect your you applications to tolerate a degree of uncertainty. After all, just guaranteeing a message was delivered to a queue doesn't guarantee it wasn't dropped by the consumer, or error in some other way.

**Comment by yqsailor** [comment]
Through testing, I found that there was no feedback on successful delivery.
Whether it's success or failure, can i get immediate results feedback?

**Comment by yqsailor** [comment]
The broker confirms the message in the following case:
1.Broker finds that the current message cannot be routed to the specified queues (if the mandatory attribute is set, broker sends basic. return first)

2.Messages with non-persistent attributes reach all queues they should reach (and mirror queues)

3.Persistent messages reach all queues (and mirror queues) they should reach and are persisted to disk (by fsync)

4.Persistent messages are consumed from all queues in which they are located (acknowledged if necessary)

When the third happens，no feedback was received. what should i do? @cressie176

**Comment by cressie176** [comment]
Hi @yqsailor 

I don't follow you...

3. Persistent messages reach all queues (and mirror queues) they should reach and are persisted to disk (by fsync)

In this situation providing you are using a confirm channel and pass a callback to the publish method (both the promises and callback variants) the callback will be executed when the server confirms. See https://www.squaremobius.net/amqp.node/channel_api.html#flowcontrol.

**Comment by yqsailor** [comment]
Hi @cressie176 
Sorry for my english!
I use the confirmChannel to publish message to exchange that not bound by any queue, but the callback err is null, how to confirm it published to the queue successfully?

**Comment by yqsailor** [comment]
Below is my code example, there is no queue to bind the exchange 'foo-exchange' , but the result is `Message acked`;
```
var open = require('amqplib').connect();
open.then(function(c) {
  c.createConfirmChannel().then(function(ch) {
    ch.publish('foo-exchange', '', new Buffer('foobar'), { durable: true },
      function(err, ok) {
        if (err !== null)
          console.warn('Message nacked!');
        else
          console.log('Message acked');
    });
  });
});
```

**Comment by cressie176** [comment]
Hi @yqsailor,

```
#publish(exchange, routingKey, content, [options])
```

What I believe has happened in your example is that the message has been successfully published to the foo-exchange. Try listening for the channel `return` event

> #on('return', function(msg) {...})

However as per my earlier comment it's not straightforward to use this even in most scenarios. If you want to pause execution until knowing the message has been delivered it won't help you - you will receive no such confirmation (unless the consumer(s) explicitly reply). You could pause execution for 1 second, with the expectation that you would have received a return event by then if the message had not been delivered, but the performance would be woeful.

Your best bet is to design your application to tolerate the uncertainty of message delivery, but to recorded and subsequently handle return events out of band.
