### ISSUE TITLE
 Error: No channels left to allocate

### ISSUE THREAD

**Issue by ddtraceweb** [squaremo/amqp.node#516]
Hello,

i updated the version of rabbitMQ 3.7.4 to 3.7.14 and i have this error : 
 Error: No channels left to allocate

Do you know why ?

this is an example of my code.

```
let Open = require('amqplib').connect(_app.settings.rabbitmq_connector);
let q = 'stat_todo';

  Open.then(function (conn) {

    return conn.createChannel().then(function (ch) {

      return ch.assertQueue(q, {durable: true}).then(function () {
        ch.sendToQueue(q, Buffer.from(msg));
        return ch.close();
      }).catch(function(err){
        console.log(err);
        return ch.close();
      });

    }).catch(function(err){
      console.log(err);
    });

  }).catch(function(err){
    console.log(err);
  });
```

**Comment by cressie176** [comment]
Hi @ddtraceweb,

It's not clear from your code sample, but it could be that you're attempting to send messages faster than creating a channel, asserting a queue, sending the message and closing the channel will allow. This means that even though your code looks like it will reliably release channels, they may be accumulating due to in flight operations. You can resolve this by throttling the messages, sharing channels or using a channel pool.

I'm not sure why you would only start seeing this after upgrading RabbitMQ. I suppose it's possible that they decreased the number of channels available per connection, or that for some reason network communication became slower in your environment.

**Comment by chrono** [comment]
I just found out about this randomly: rabbitmq changed the default max channel in a point release (3.7.5) https://github.com/rabbitmq/rabbitmq-server/issues/1593

So if your app has a real need for more channels you need to raise it on the server side via something like `channel_max=65535` which would be the protocol level max (it's defined as unsigned short in the protocol spec).

**Comment by cressie176** [comment]
@ddtraceweb did you manage to resolve the issue?

**Comment by ddtraceweb** [comment]
ok it's resolved.
