### ISSUE TITLE
Prevent duplicate messages maybe?

### ISSUE THREAD

**Issue by beratuslu** [squaremo/amqp.node#523]
In my project I am planning to take Web Worker / Service Worker approach to be able do "Zero down time update" and scale my app in the future easily.

For messaging between workers I am planning to use amqplib module. Which I am quite beginner in RabbitMQ, Pub/Sub, Messaging stuff.

To be able to scale application and "Zero down time update". All workers should be stateless. So For this I am taking JWT approach for my API. So for so good. But in my application, I have to listen external 3rd party API socket connection for every single user in my application. So my questions:

1. What is the correct approach for scaling "Sockets Listening Worker".(Even I am not sure if it should be a separate worker).
2. When I update this "Sockets Listening Worker" pm2 will try to just run 2 instance of this worker to make update for "Zero down time". In this scenario opening possibility of 2 same socket sending same message to RabbitMQ task queue.

How can I prevent duplicate messages in amqplib?
And can you provide some example for messaging between workers in nodejs?

Did I explain issues right?

**Comment by cressie176** [comment]
Hi @beratuslu,

I'm very sorry, but after reading your question a few times I still don't understand your proposed architecture. Can you explain (or link to definitions of) the following please

* Zero down time update
* Sockets Listening Worker

I'm also confused why 

* JWT is relevant
* you need to establish a connection to the 3rd party API for every user in your application (it doesn't sound like it will scale very well).

Regarding your specific amqplib questions...

> How can I prevent duplicate messages in amqplib?

There is nothing in amqplib that will detect or prevent duplicate messages. You will either need to ensure you don't publish the same message twice, or safely handle duplicates on consumption. The latter is often the best approach, since it's also possible for RabbitMQ to redeliver messages that haven't been acknowledged by the consumer.

> And can you provide some example for messaging between workers in nodejs?

There are some examples [here](https://github.com/squaremo/amqp.node/tree/master/examples) and [here](https://www.rabbitmq.com/tutorials/amqp-concepts.html). Since you're unfamiliar with RabbitMQ, I strongly suggest you read about [AMQP Concepts](https://www.rabbitmq.com/tutorials/amqp-concepts.html) and cloudamp's [beginners guide](https://www.cloudamqp.com/blog/2015-05-18-part1-rabbitmq-for-beginners-what-is-rabbitmq.html) ) first. Once you've understood the basics then read through the relevant sections of the [amqplib channel api](https://www.squaremobius.net/amqp.node/channel_api.html).
