### ISSUE TITLE
State of recovery (either built-in or guidance)?

### ISSUE THREAD

**Issue by hardcodet** [squaremo/amqp.node#529]
I'm new to RabbitMQ with node.js, and I'm finding myself faced with the question probably every developer has: How do I make that thing reliable to not crash and burn my service if there's a hiccup (temporary connection loss on the client, host rebooting, etc. etc.)?

I'm seeing multiple open PRs, external libraries, snippets etc, but I still don't know what route I should take. Before I reinvent a wheel that probably was built thousands upon thousands of times, I'd be super glad to get some guidance or pointer in the right direction before going down that rabbit hole, and risking missing some crucial things :)

**Comment by KristjanTammekivi** [comment]
The one gotcha that you have to listen to error events on channel/connection, otherwise your app will exit when an error is emitted (explanation: https://nodejs.org/api/events.html#events_error_events)

**Comment by cressie176** [comment]
Hi @hardcodet,
A good question. It's unfortunately a bit of a minefield.

### Poisoned Messages
If your application consumes a message that causes it to crash, before the message is acknowledged, it will be rolled back to the front of the queue, and re-consumed when your application restarts, causing it to crash again. RabbitMQ can easily deliver 1000 messages/s so the crash/restart loop can cause havoc with infrastructure & CPU load. The most effective way I've found to prevent this is to

1. Publish messages with a message id
2. Maintain an external count of redelivered messages
3. Immediately nack messages that have been redelivered more than X times
4. Route nack'd messages to a dead letter queue

### Consumer Flooding
If your application consumes messages without setting a prefetch, it will attempt to consume all messages concurrently. This can bust the call stack and/or memory. The most obvious solution is to set a prefetch and explicitly ack each message

### Publisher Flooding
You can get into a similar problem to consumer flooding if you consuming data from a different source (e.g. documents from mongo) at a faster rate than you can publish messages. The solution is to ensure you're built in some kind of back pressure.

### Graceful Start Up / Shut down
If your application uses other backing services (e.g. consumers a message then writes to a db) it's worth considering start-up order. You will want to be sure that the database connection has been successfully established before consuming from a queue. Conversely you will want to make sure that you have stopped consuming, and any inflight messages have been successfully processed, before the database connection has been dropped. The latter is quite hard with RabbitMQ it's not always easy to count messages out (especially if your workflow ends up publishing a message).

### Connection Recovery
If the RabbitMQ connection (or channel) drops, you need to reconnect, and resubscribe any consumers. If you're likely to have 100s of connections, and a cluster of RabbitMQ nodes, then it's worth putting some thought into how to safely distribute connections between nodes. A reasonable approach is to have the client randomly connect to a different node when it receives a connection error, and to implement a capped incremental backoff if the re-connection fails.

### Message Loss
To minimise chance of message loss you need to ensure that both queues and messages are persistent. When publishing you may want to use confirm channels. You can also make queues highly available (which means messages will be automatically duplicated), but there's no easy way to ensure you don't lose messages in the event of a network partition. See the bottom of [this article](https://aphyr.com/posts/315-jepsen-rabbitmq) for an explanation.

### General Error Handling
When processing messages, it's possible you will encounter business or technical errors. Most messages that aren't a problem with the message payload tend to be recoverable, but sometimes require manual intervention. Therefore a good approach is to dead letter messages that caused an unrecoverable error (e.g. payload validation failed), but to perform a delayed retry for recoverable ones. Doing this well with RabbitMQ is complicated, as you don't want to "hold" the message in your application since it will use one of your prefetch allocations. One approach is to forward the message to a queue with an x-message-ttl and dead letter configuration to route back to the original queue.

### Message Order
RabbitMQ does guarantee message order, in as far as messages will be delivered in the same order that they are received, but this guarantee is practically worthless in a real environment, since node will handle messages asynchronously and you are likely to want to replay a dead lettered or recoverable message at some point. A good solution is to version messages at source, and implement a combination of upsert / version based concurrency control when consuming.

I maintain a wrapper for amqplib called [Rascal](https://github.com/guidesmiths/rascal). It does a reasonable job of  

* Poison message protection
* Flood protection
* Connection recovery
* General error handling
* Message loss protection

It doesn't help with network partitions, message order guarantees or counting out messages for graceful shutdown. The configuration can also get quite bloated.

**Comment by hardcodet** [comment]
@cressie176 sorry for waiting so long with the feedback - thanks a ton for the detailed response! We're definitely having a look at rascal :)
