### ISSUE TITLE
How to cleanly close channels and connections?

### ISSUE THREAD

**Issue by natvaldev** [squaremo/amqp.node#550]
As part of my test suites, I need to close the connection and the channels.
I'm doing so like this:

```js
...
async start () {
  await this.connect()
}

async stop () {
  await this.channel.close()
  await this.conn.close()
}
```

Where `channel` and `conn` are the channel and the connection relatively.
Executing the `stop` function after a test resolve this warning:

```
console.warn node_modules/bluebird/js/release ...
  Unhandled rejection Error: Channel ended, no reply will be forthcoming
    at rej (...)
    ...
```

How can I close `amqplib` connection without logging warnings?

**Comment by cressie176** [comment]
Hi @natvaldev,

It's probably not the `stop` function causing the issue, but more likely that something in your test or the application under test is attempting to use the channel after it has been closed. This is often because your test is completing too early. Some people add a setTimeout to the test, but I prefer to find or manufacture an observable event that signifies the natural end of a unit of work. In more complicated cases it can be because a previous test has not been fully torn down and is being stimulated by another.

**Comment by cressie176** [comment]
@natvaldev did you resolve your problem?
