### ISSUE TITLE
#checkExchange(exchange) Interrupts Promise Flow Unless #on('error', ..) Set

### ISSUE THREAD

**Issue by ryandanielspmc** [squaremo/amqp.node#555]
When calling `channel.checkExchange`, catching the error in the flow of the promise is not possible unless `channel.on('error' ...)` is set. The application exits with error unless there is an `'error'` handler. I would expect the `'error'` handler to be optional instead of mandatory.l

**Comment by cressie176** [comment]
Hi @ryandanielspmc,

A wide variety of connection and channel errors can occur independently from application code paths, so error handling using a purely `catch` based approach would be insufficient. I suspect this is why the `.on('error')` approach was taken. I appreciate this can be surprising, but it's unlikely to change now and is at least [documented](https://www.squaremobius.net/amqp.node/channel_api.html#failure).

**Comment by ryandanielspmc** [comment]
@cressie176 

What I am implementing is a retry at the end of the promise chain starting from the connection, via `await`. This allows me to reconnect and try again with out adding another layer to the call stack. It is my understanding that JS does not implement TCO, so simply executing my entry point from `on('error', ...)` would eventually cause a stack overflow. So, in this case, I am simply handling the `'error'` event, and just logging it, then that allows the promise chain to work properly, and allow the retry to work.

I would argue that allowing the error to propagate down the promise chain, instead of making it a side effect, would more align with the spirit of `Promise` and its monadic computation composition. This aligns much more with the behavior of functional programming, where `Promise` is _**roughly**_ equivalent to `Either`, where you only have an end result of `Right` for success, and `Left` for failure.

**Comment by cressie176** [comment]
Hi @ryandanielspmc,

What you describe sounds like a reasonable way to use amqp, but not the only way. For systems with high throughput it's common to establish a semi-permanent connection and channels, then based on external triggers (e.g. inbound HTTP requests) publish messages using the shared resources. Under these circumstances you need a way to detect errors which happen **outside of promise/callback chains**. This I suspect is the reason for the event based error handling. It is still possible to add reconnection/retry logic, but not as straightforward as you may wish.  It's also possible that a mixed approach to error handling might have been better, but I suspect arguing for an alternative design at this stage is rather pointless.

**Comment by CaptainHansen** [comment]
We are trying to use this library in conjunction with RabbitMQ to handle sending password reset/password changed emails to our end users.

`assertQueue()` is also affected - took me a few hours of frustration to figure out what the issue was.  In the end result our error catcher was reporting duplicate errors - the error reported by the promise rejection, and the "unhandled" rejection generated due to there not being a `.on('error'` handler in our code.  If it wasn't for this issue being reported I probably wouldn't have found the solution.

I also have a feeling that using a throw-away handler in `.on('error'` may be a bad thing because i've seen rejections occur after the promise chain resolves because `.sendToQueue()` does not return a promise.  Because of this, an `ACCESS-REFUSED` error raised due to insufficient permissions to write to a queue is only reported via `.on('error'` which prevents us from passing the error along to the end user.  In this case, the end user thinks the email was queued even though it wasn't).  I'm stuck for now with this library because using a throw-away handler would prevent certain errors from appearing in kibana, yet I also don't want duplicate error messages to appear, AND we need the promise chain to correctly resolve or reject to pass the word along to our web app reporting whether or not the email was successfully queued.

**Comment by cressie176** [comment]
I've created an [example app](https://github.com/cressie176/amqplib-express-example) demonstrating how you can use express and amqplib with connection recovery. It's not perfect (for example, I don't like that I always close the connection irrespective of whether a channel error or connection error was emitted), or that all edge cases are covered, but it should provide an idea of how to progress.

I also didn't love pRetry - it doesn't provide an infinite retry option and when I set the number of retries to Number.MAX_SAFE_INT is actually crashed node.

**Comment by cressie176** [comment]
I've updated the [example app](https://github.com/cressie176/amqplib-express-example) to timeout if the publish is not acknowledged within 1 second. 

I'm closing this issue as despite the complexity of using both promises/callbacks and event emitters for handling errors there aren't any practical alternatives. As demonstrated, it's possible to get things working without too much trouble once the relevant patterns are understood.
