### ISSUE TITLE
error event seems not emitted when connection closed by server

### ISSUE THREAD

**Issue by warrenwyf** [squaremo/amqp.node#598]
When the connection is closed due to a server problem, the error event can not be caught, however, the close event can.

connection.on('error', err=>{
  console.log('error') // not invoked
})

connection.on('close', ()=>{
  console.log('close') // invoked
})

**Comment by GiltosMx** [comment]
I think this might be related to a change introduced by #110. Another issue was created asking about something similar to this in #199. Maybe those issues can help answer your question, but from what I can gather the `error` event should only be emitted when something `exceptional` happens with your server. The `close` event should be emitted when something `unexceptional` happens - and you don't want your application to crash, such as an intentional server restart.

**Comment by mikl** [comment]
I’ve noticed this happening to my application. The RabbitMQ server is restarted for an update, but my consumer Node.js process never notices or reconnects, so essentially just stops consuming.

I guess I just assumed that a connection failure would be considered an error. Maybe it should be, if there’s nothing listening for the close event, since this will lead to strange silent failures.

**Comment by warrenwyf** [comment]
According to the doc, when the server closes the connection, no error event is emitted, but a close event with an error is emitted instead. 

So what we should do is like this:

``` javascript
conn.on('error', (err) => {
    // Do something, like reconnect
});

conn.on('close', (err) => {
      if (err) {
            // Do something, like reconnect
      }
});
```
Hope it will be helpful.
