### ISSUE TITLE
Batch consumer

### ISSUE THREAD

**Issue by guicuton** [squaremo/amqp.node#600]
Is there some way to batch consumer?
For example:

```javascript 
amqp.consumeQueue(SMS_CALLBACK_QUEUE, parseInt(AGREGATOR_TPS_100), (message) => {

  let messageData = JSON.parse(message.content.toString())

  let api = new Webhooks(CALLBACK_ENDPOINT, 'callback-sent', message)
  api.sendMessage(messageData)

})
```
This is my callback function from `channel.consume`
This only fires my class Webhook (with axios request for some endpoint) for every message received and sometimes, i will have more than 10k of messages that will do 10k of http request to another external API.

There is another way to do this?

I've already tried with setInterval but didn't work, because when i clear the array inside of setInterval, it already can have new itens pushed from consumeQueue that makes me loose some itens

Example that didn't work:

```javascript
/**
* Queue name,
* Prefetch number,
* callback
* /
var messages = []
amqp.consumeQueue(CALLBACK_QUEUE, parseInt(AGREGATOR_TPS_100), (message) => {

  let messageData = JSON.parse(message.content.toString())
  messages.push(messageData)
  
  //Ack individual message
  amqp.messageAck.delivery(message)

})

//Send messages each 5 seconds
setInterval(() => {

  if(messages.length > 0) {

    let api = new Webhooks(SMS_CALLBACK_ENDPOINT, 'callback-sent - '+messages.length)
    api.sendMessage(messages, true)

    messages = []

  }
```

**Comment by cressie176** [comment]
Hi @guicuton,

You could take a couple of approaches...

1. Write messages to a store (in-memory or external), then publish them as a batch. This is what you tried to do with set interval, but as you noted, you need to take a different approach than wiping the entire store whenever you send.

2. Use channel.get instead of channel.consume. This way instead of messages being pushed to your application they will be pulled.

In either case you need to be deliberate about when you acknowledge the message. If you acknowledge the RabbitMQ messages before calling the webhook, you will lose them if you application terminates. If you acknowledge after, then you could send duplicates.

**Comment by guicuton** [comment]
Hi @cressie176 
Thank you for direction!

I've made something like:

```javascript
var messages = []
const consumeBatch = async () => {
  //Get 100 messages as  limit
  for(var i = 0; i < 100; i++) {
    amqp.getQueueMessages(CALLBACK_QUEUE, (message) => {

      if(message !== false) {

        let messageData = JSON.parse(message.content.toString())
        messages.push(messageData)
        amqp.messageAck.delivery(message)

      }

    })
  }
  return messages
}

//Request function each 5 seconds
setInterval(async () => {
  console.log('Waiting batch')
  let received = await consumeBatch()
  if(received.length > 0) {
    console.log('Batch send. Volume: %s', received.length)
    console.log(received)
    messages = []
  }

}, 5000, messages)
```

I do not know if is the best aproach, but with this i've achieved what i needed.
Get the maximum of X messages at each X seconds

**Comment by cressie176** [comment]
Glad you got it working. I know this is not your exact code, but a few things to consider in case they are repeated...

1. You are making 100 getQueueMessages concurrently, did you really mean to do this? If not you might want to use [async.eachLimit](https://caolan.github.io/async/v3/docs.html#eachLimit) or [async.doWhilst](https://caolan.github.io/async/v3/docs.html#doWhilst).

1. You are not short circuiting if the message is false. It's slightly tricky to do this with [async.eachLimit](https://caolan.github.io/async/v3/docs.html#eachLimit), people used to yield `true` instead of an error to indicate `done`, but I'm not 100% sure this is still supported.

1. Are you 100% sure the message content will always be JSON? If not, your application will crash and the bad message will be rolled back. When you restart the application, the message will be redelivered crashing your application again. If there is a slight chance the message could be invalid, I tend to log it and nack it.

1. You are acknowledging messages before sending the batch. If you application crashes those messages will be lost forever. Is this what you intended?

1. If sending the batch takes longer than 5 seconds, two setIntervals will run concurrently mutating the shared messages array, and you are likely to loose messages. Maybe use setTimeout instead, and reschedule when you successfully complete the batch.

1. I am confused by your use of `received` and two uses of `messages`. messages is declared on line 1, updated in consumeBatch, assigned to `received` and passedToSet interval. You don't declare any function parameters in the setInterval task however. There was no need to assign it to `received` since `messages` was already in scope.

1. Are you handling connection / channel errors else where in your code? Unless you remember to add error handlers, they will crash your application. At some point you'll have a connection drop, and I usefully find its simplest to log the error, then gracefully shut the application, then automatically restart it.

**Comment by guicuton** [comment]
Hi @cressie176 

About your questions:

1 - I never used this dependencie. I'll se how it works and implement.

2 - I'll read about it

3 - Yes! All the messages are published by another endpoint that always push json content

4 - Not all! The ack that i've posted was just a sample. I'll ack the message only after Axios Post return true.

5 - This is something whati've figured that can happen, so the indication to use the async.eachLimit probably will resolve it.

6 - I'm 100% with you! This is something that i'll fix it!

7 - Yes! On the connection side i have listeners from errors and then log it to try auto restart if some error is fired

Soon i'll put here the results!
Thank you so much so far!

**Comment by guicuton** [comment]
Hi @cressie176 

Look what i achieved:

```javascript 

var messages = []
var acks = []

//Callback function that will use my class to require my endpoint
/**
   * @param {array} messages - Messages batch to be send by Axios Post 
   * @param {array<object>} - Acks objects on array to be iterated and ack all messages
*/
var requestWebhook = (messages, acks, callback) => {

  try {
    
    if(messages.length > 0 && acks.length > 0) {

      let api = new Webhooks(CALLBACK_ENDPOINT, 'Webhook Callback. Volume: '+messages.length, acks)
      api.sendMessage(messages, true)

      callback(true)

    }

  } catch (err) {
    console.error('Error. %s', err)
  }

}

setTimeout(getMessages = async () => {

  //Queue consumer with prefetch on 100 messages
  amqp.consumeQueue(SMS_CALLBACK_QUEUE, parseInt(AGREGATOR_TPS_100), (message) => {
    
    //Parse message to JSON (100% sure that always will came on JSON format)
    let messageData = JSON.parse(message.content.toString())
    
    //Push individual messages
    messages.push(messageData)

    //Push message object to ack further
    acks.push(message)

  })

  if(messages.length > 0) {

    async.each(messages, function(item, callback) {

      requestWebhook(messages, acks, (response) => {
        
        //If response is true on callback function i clean the arrays and "restart" the channel consumer
        if(response) {

          messages = []
          acks = []

          setTimeout(getMessages, 5000)

        }

      })

    }, (err) => {
      if(err) {
        console.error('Error %s', err)
      }
    })

  } else {
    console.log('Waiting new messages...')
    setTimeout(getMessages, 5000)
  }

})
```

Here is my Webhook class that request my endpoint using Axios and if all goes fine, ack the message array
```javascript 
module.exports = class Webhooks {

  constructor (endpoint, worker, acks = false) {
    this.endpoint = endpoint
    this.acks = acks 
    this.worker = worker
    this.date = new Date(Date.now())
  }

  sendMessage (data, multiple = false) {

    axios.post(this.endpoint, data).then((response) => {

      if (this.acks !== false) amqp.messageAck.delivery(this.acks, multiple)
      console.log('Webhook: %s - Date: %s', this.worker, this.date.toTimeString())

    }).catch((error) => {

      if (this.acks !== false)  amqp.messageAck.reject(this.acks)
      console.error('Error on %s webhook - Error: %s', this.worker, error.toJSON())

    })

  }

}
```

Here is my custom function that i'm using to ack the messages:
```javascript 
const messageAck = {

  delivery: async (message, multiple = false, conn = connect) => {

    let channel = await conn

    if(multiple) {
      message.forEach((ack) => {
        channel.ack(ack)
      })
    } else {
      channel.ack(message)
    }

  },

  undelivery: async (message, conn = connect) => {
    let channel = await conn
    channel.nack(message, true)
  },

  reject: async (message, conn = connect) => {
    let channel = await conn
    channel.reject(message, true)
  }

}
```

I do not know if i'm using the best approaches, but with your help/comments i've made a lot of changes.
If you have any new considerations, please, i'll glad to hear it.

Regards
