### ISSUE TITLE
Throttle Producer using flow control example

### ISSUE THREAD

**Issue by figuibej** [squaremo/amqp.node#601]
I have a process that read from database millions of records very quickly and in the other hand have slow consumers, i have to balance the rate of produciton / consumption to avoid message loss, so i see that amqp has the flow control feature and im not sure how to implement using amqplib, in the [api reference#flow-control](https://www.squaremobius.net/amqp.node/channel_api.html#flowcontrol) says that publish and sendQueue has a flag that allow to keep send a messages, and the channel has 'drain' event to resume.

i test a new queue with a `x-max-length` in 10000 and `overflow-behavior` in `reject-publish` my expectation is when the queue size reach the x-max-length the producer stop, throttle or whatever **but i do not want to lose any message, is critical**.

i suppose that is a very common feature but i appreciate if anyone can provide a good example, considering what configuration use to amqplib and also which configuration of rabbit have to use for achive that

**Comment by cressie176** [comment]
Hi @figuibej,

I believe the flow control is triggered when the channel's buffer gets full, not when a queue reaches a certain size. I've never tried the `reject-publish` feature, but guess you need to use a confirm channel when publishing the message and supply a callback to the publish function. I would expect the callback to be called with an error if the broker responds with a `basic.nack`.Assuming this is correct, on receiving the error you could reset the message in your database and pause production.

However I suggest you might consider an alternative approach. Attempting to protect a consumer but throttling a producer couples both systems, and still means (in your examples) your consumers will be working through the 10,000 messages as fast as they can. i.e. you haven't really throttled the consumers at all.

An alternative approach however is to publish messages without restriction, but to throttle the consumers. You can do this with RabbitMQ by using explicit consumer acknowledgements and setting the consumer's channel prefetch to a number you are confident they can handle. Prefetch means that RabbitMQ will pause delivery when there are that many unacknowledged messages. If you set this to 1, you can have 1,000,000 messages on the queue and each consumer will still only process one message at a time.

Not losing any messages is a slightly different problem. You should ensure you have persistent queues, and only send a consumer acknowledgement once the message has been successfully handled. For this reason your consumer also needs to be able to tolerate duplicates, since if your application is killed when messages are still being processed, they will be redelivered when your application restarts.

Persisted messages can still be lost if you lose your disk. To get around this RabbitMQ introduced High Availability (HA) queues, however there were still issues if you get a network partition. More recently they have introduced quorum queues, which I think resolves this, but I haven't had a chance to use them yet. Quorum queues also have the advantage of being able to dead-letter messages which fail repeatedly, which is extremely useful in case the producer ever publishes a message which would repeatedly crash the consumer.

**Comment by FerLuisxd** [comment]
Hey @cressie176. Question And how can I create a Quorum queue using this lib?

**Comment by cressie176** [comment]
@FerLuisxd you need to set the x-queue-type argument to quorum when declaring the queue. See [here](https://www.rabbitmq.com/quorum-queues.html#declaring)
