### ISSUE TITLE
How does amqp buffer works?

### ISSUE THREAD

**Issue by igorfv** [squaremo/amqp.node#61]
First of all, this is the first time I'm using rabbit and I'm a little bit lost. I need to parse a file (500k lines) and send it to Rabbit, but it will only start sending the messages after I finish parsing every line.

Is there any way to flush every 5k messages or something like that?

```
var amqp = require('amqplib');

var i = 0;
var totalMessages = 500 * 1000;
var q = "items";

amqp.connect('<SERVER>').then(function(conn) {
  var ok = conn.createChannel();
  ok = ok.then(function(ch) {
    ch.assertQueue(q);
    ch.prefetch(100);

    while(i < totalMessages) {
      i++;
      var msg = i + "...";
      ch.sendToQueue(q, new Buffer(msg));
      console.log(i);
    }
  });
  return ok;
}).then(null, console.warn);
```

**Comment by austince** [comment]
Hey, thanks for the above help @squaremo! Is it possible to increase the size of the write buffer or will that not have any benefit as it is flushed as fast as possible?

**Comment by squaremo** [comment]
It's not possible to increase the size of the write buffer for a channel, though it starts pretty big already (~1000 frames, so at the default frame size, 4MB or so) anyway. It would not be hard to add this ability -- just a matter of wiring through an argument from `new Channel()` to `Connection.freshChannel()`.

But in doing so, you will lose sensitivity to backpressure, meaning messages spend longer in the buffer and more are at risk of being lost if you crash. The number above is arbitrary of course, so it's possible that it's not the right number for a given circumstance -- only careful calculation and experimentation would determine that.

**Comment by austince** [comment]
Thank you for the thoughtful answer. Is this something you would accept a patch for or would you rather leave it as to not allow accidental adjustments where there hasn't been careful consideration?

**Comment by austince** [comment]
Ok :) If I have time I might try to create a well-documented patch in the next few weeks.

**Comment by rraina** [comment]
@squaremo @austince  -- I updated this to using Promises if helpful
```
var amqp = require('amqplib');

var i = 0;
var totalMessages = 500 * 1000;
var q = "items";

const conn = await amqp.connect('<SERVER>');
const channel = await conn.createChannel();
channel.assertQueue(q);

var sent = 0;

for (; sent <= totalMessages; sent++) {
  const isSuccess = channel.sendToQueue(q, new Buffer(sent + '..'));
  if (!isSuccess) { 
    await new Promise(resolve => channel.once('drain', resolve));
    sent--; // so that we resend the message that failed
  }
}
````

**Comment by bluEEil** [comment]
> ```js
> var amqp = require('amqplib');
> 
> var i = 0;
> var totalMessages = 500 * 1000;
> var q = "items";
> 
> amqp.connect('<SERVER>').then(function(conn) {
>   var ok = conn.createChannel();
>   ok = ok.then(function(ch) {
>     ch.assertQueue(q);
> 
>     var sent = 0;
> 
>     function go() {
>       var keepGoing = true;
>       while (keepGoing) {
>         if (sent >= totalMessages) return;
>         keepGoing = ch.sendToQueue(q, new Buffer(sent + '...'));
>         sent++;
>       }
>       ch.once('drain', go);
>     }
>     go();
>   });
>   return ok;
> }).then(null, console.warn);
> ```

I'm really puzzled regarding how to use amqlib for sending a message to a channel (sendMessageToChannel/Publish)
at first I didn't use any flow control for the Stream behavior but after reading this post and reading 
* http://www.squaremobius.net/amqp.node/channel_api.html#flowcontrol
I thought I might need it since my system can get to a point where many messages will be sent at the same time using the same channel. What I did was this:
`/**
     * This method will wrap sendToQueue of amqlib and handle the case when the stream buffer is full and not
     * ready to send a message.
     * It's a bit weird that this is needed but that's just how the amqlib works, you can read more about
     * this here:
     * http://www.squaremobius.net/amqp.node/channel_api.html#flowcontrol
     * Solution inspired by:
     * https://github.com/squaremo/amqp.node/issues/61#issuecomment-439597328
     * @param channel
     * @param queue
     * @param content
     * @param options
     * @param numOfRetries
     * @return {Promise<void>}
     */
    static async sendToQueueSafe(channel, queue, content, options = {}, numOfRetries = RabbitConn.SAFE_ACTIONS_NUM_OF_RETIRES) {
        const isSuccess = channel.sendToQueue(queue, content, options);

        await RabbitConn._channelStreamBehaviorWrapper(channel, isSuccess, numOfRetries, () => {
            return RabbitConn.sendToQueueSafe(channel, queue, content, options, numOfRetries- 1);
        });
    }

static async _channelStreamBehaviorWrapper(channel, isSuccess, numOfRetries, retryCb) {
        if (!isSuccess) {
            log.error(`ZIV FAILURE SENDING MESSAGE, RETRY: ${numOfRetries}`);
            if (numOfRetries === 0) {
                throw new Error(`Failed to send data over RabbitMQ channel stream, retry amount exceeded`);
            }

            await new Promise(resolve => channel.once('drain', resolve)).timeout(RabbitConn.SAFE_ACTIONS_TIMEOUT);
            return retryCb();
        }
    }`

I did a manual load test on this by sending 200k message with batches of 5k each (using Promise.all to wait for each batch to finish). Each message is a sort of RPC I have in my system (so the message goes to a queue for consumer X who process it and sends the result back to consumer Y which reads the result).

In the log I could see that the number of retries indeed goes down from 50 to 42~ and then everything just hangs and the batch (5k) never finishes. Note I have a large timeout on the drain registeration so I don't count on the timeout to "bail" me here, might be that the drain event just doesn't occur for all messages in this scenario so it all hangs.

I'm really puzzled by this behavior and not sure how to implement this (I need sendToQueueSafe to be called many times by different flows but on the same channel)

If I do the same test but change sendToQueueSafe to:
`static async sendToQueueSafe(channel, queue, content, options = {}, numOfRetries = RabbitConn.SAFE_ACTIONS_NUM_OF_RETIRES) {
        const isSuccess = channel.sendToQueue(queue, content, options);

        // await RabbitConn._channelStreamBehaviorWrapper(channel, isSuccess, numOfRetries, () => {
        //     return RabbitConn.sendToQueueSafe(channel, queue, content, options, numOfRetries- 1);
        // });
    }`

Then my load tests are successful (inspite I know that isSuccess is false sometimes) so I'm even more puzzled, is this flow control mechanism already implemented inside amqlib?
Could really appreciate if someone enlighten me on this (and maybe update the official docs to be more clear on this and how to flow control?)

**Comment by simondutertre** [comment]
> @squaremo @austince -- I updated this to async/await syntax if helpful
> 
> ```
> var amqp = require('amqplib');
> 
> var totalMessages = 500 * 1000;
> var q = "items";
> 
> const conn = await amqp.connect('<SERVER>');
> const channel = await conn.createChannel();
> channel.assertQueue(q);
> 
> for (let sent = 0; sent <= totalMessages; sent++) {
>   const isSuccess = channel.sendToQueue(q, new Buffer(sent + '..'));
>   if (!isSuccess) { 
>     await new Promise(resolve => channel.once('drain', resolve));
>     sent--; // so that we resend the message that failed
>   }
> }
> ```

@squaremo Can you confirm that in this example the decrement of 'sent' variable is wrong ? ( false means  Buffer is getting full, not that sending the message failed ? )

**Comment by marcFernandez** [comment]
Hi @simondutertre, have you found out if the decrement is right?

My assumption is that it should be right because if you keep publishing/sendingToQueue messages, the return value will keep being false until the drain event is emitted and these messages won't be written to the queue. It would be weird to only implement the retry logic when false has been received 2 or more consecutive times, wouldn't it?

**Comment by boris93** [comment]
> > @squaremo @austince -- I updated this to async/await syntax if helpful
> > ```
> > var amqp = require('amqplib');
> > 
> > var totalMessages = 500 * 1000;
> > var q = "items";
> > 
> > const conn = await amqp.connect('<SERVER>');
> > const channel = await conn.createChannel();
> > channel.assertQueue(q);
> > 
> > for (let sent = 0; sent <= totalMessages; sent++) {
> >   const isSuccess = channel.sendToQueue(q, new Buffer(sent + '..'));
> >   if (!isSuccess) { 
> >     await new Promise(resolve => channel.once('drain', resolve));
> >     sent--; // so that we resend the message that failed
> >   }
> > }
> > ```
> 
> @squaremo Can you confirm that in this example the decrement of 'sent' variable is wrong and will generate dupplicates ? ( false means Buffer is getting full, not that sending the message failed ? )

It seems that decrementing is wrong. This thread is relevant: https://github.com/amqp-node/amqplib/issues/398#issuecomment-350860245
