### ISSUE TITLE
What's the maximum number of concurrent messages being processed?

### ISSUE THREAD

**Issue by seanyu4296** [squaremo/amqp.node#616]
Hi,

Thank you guys for the awesome library. I am playing around with prefetch and I want to configure it correctly based on the workload and type of work the consumer will do.

Can I ask:

What's the maximum number of concurrent messages being processed? What determines the number of concurrent messages being processed? Is it dependent on the task so let's say i am doing a single http call when i receive a message. the maximum concurrent messages being processed will be max to 4 because the default nodejs worker pool is 4?

Setup:
- set `prefetch` to no limit
- use `channel.consume` to consume message

Scenario:
- properly setting a good prefetch count for a worker that sends http calls

**Comment by cressie176** [comment]
Hi @seanyu4296,

I haven't checked, but I suspect that amqplib doesn't make use of the worker pool. From [reading this](https://nodejs.org/en/docs/guides/dont-block-the-event-loop/) it seems that the pool is typically used for CPU intensive tasks or blocking IO operations. I don't expect dequeuing a message fits into either of these categories. 

Without prefetch, I believe that RabbitMQ will keep delivering messages as fast as it can, adding work to the event loop. If your application processes those messages more slowly than they are added, it will eventually run out of memory and crash, or potentially starve other parts of your application so that they do not work as expected.

With a prefetch, the throttling is done by the broker, and only meaningful when you disable auto acknowledgements. A prefetch of N means there will be at most N number of unacknowledged messages delivered for that consumer.

Hope that helps.

**Comment by seanyu4296** [comment]
Ah I see. Thanks for sharing your insightful knowledge on the matter @cressie176 

What would you recommend to be a good prefetch value or a way to finding a good/optimal prefetch value for queue consumer workers that only does a couple of sequential HTTP calls? 

Thank you again.

**Comment by cressie176** [comment]
Hi @seanyu4296,

The best thing to do would be to load up a queue with messages in a realistic test environment and experiment with different prefetch values while monitoring the applications performance and event loop lag. If you can, you might also want to monitor the server(s) you are sending the HTTP requests to. Due to its asynchronous nature, your application could easily end up sending 1000s of requests a second, and depending on the server capability you might end up flooding it.

If this is too hard, then you could start with a low prefetch and monitor the queue length. If the queue length grows, then increase the prefetch gradually.

**Comment by seanyu4296** [comment]
Ohhh I see that helps alot especially coming from one of the core maintainers @cressie176 of the lib! 🙏 

Thank you

I'll also leave some references I found that might help others

https://www.rabbitmq.com/confirms.html#channel-qos-prefetch-throughput
https://www.cloudamqp.com/blog/how-to-optimize-the-rabbitmq-prefetch-count.html
https://www.rabbitmq.com/consumer-prefetch.html
https://www.squaremobius.net/amqp.node/channel_api.html#channel_consume

**Comment by cressie176** [comment]
I suppose another way of considering the problem, is to check or estimate the average size of the payload, then multiply this by the proposed prefetch - this should give you a rough idea of how much memory your app will need above its base level. This of course won't help throttle the remote HTTP server though.

**Comment by cressie176** [comment]
One more thing to consider - the higher prefetch, the more inflight messages you'll have if the channel dies, application crashes or is otherwise shutdown suddenly. You can't do much about the first two scenarios, but you could write your application in such a way that on shutdown it cancels consumption, and allows for any inflight messages to drain before exiting.

**Comment by seanyu4296** [comment]
Thanks for adding more valuable insights on prefetch @cressie176 ! 

> This can mean that some HTTP requests are made twice, and the remote HTTP server should be designed to tolerate this.

Yeah I guess idempotency is needed for this case

**Comment by seanyu4296** [comment]
I'll close this for now since i think it has good insight and info already
