### ISSUE TITLE
Confirm channel callback when publish/sendToQueue returns false

### ISSUE THREAD

**Issue by ssukienn** [squaremo/amqp.node#636]
Hi, I have a question regarding callback confirms of ConfirmChannel. In the source code, the provided callback is pushed to the unconfirmed array regardless of the return of publish/sendToQueue channel methods.

What happens with said callback in the scenario where publish returns false because stream is full. Message will never be sent and you should write again to channel after drain event. But callback for not sent message has been already pushed. Will it ever be called before the channel close? Will it be taken out of the unconfirmed callbacks array otherwise?

Is it correct to call it on channel close even when the related message was not sent?

Could you explain it to me? I am afraid I am missing something here and would like to understand the concept.

Additionally, I have a question related to the confirmation itself. How can we be certain that rabbit broker will issue such confirmation and it will be received by our publisher? Can it be lost due to a network partition or in some other scenarios?

Thanks!

**Comment by cressie176** [comment]
Hi @ssukienn,

I believe that just because the publish returns false, doesn't mean that the message will never be sent. I think it's just a polite way of saying backoff please, and warning that if you don't you may run out of memory.

Regarding your second point, you cannot be certain that the broker will issue a confirm, furthermore you cannot tell how long it will take to confirm, or be certain that you will receive it (the connection could drop while it is on route, or your application could crash). You only know that if you do receive a confirm, the message has been received by the broker, written to disk if persistent and replicated to the other nodes in the cluster if HA.

**Comment by ssukienn** [comment]
Thanks for the reply @cressie176,

The second part is totally understandable and what I anticipated.

But with the first. Okay... So just to be certain I am following you. In fact you don't need to do a resend after publish/sendToQueue returns false? This message is not really lost (by lost I mean like discarded by the lib itself) even with the full stream? And will be sent by the amqplib when the stream will emit drain? Without my intervention?

**Comment by cressie176** [comment]
> This message is not really lost (by lost I mean like discarded by the lib itself) even with the full stream.

This is my understanding. There's nothing in the documentation which says the message is lost, only that publishing a message behaves like stream.Writable, the documentation for which can be found [here](https://nodejs.org/api/stream.html#stream_writable_write_chunk_encoding_callback), and indeed says that it is possible, but not recommended to continue writing after high watermark has been passed. Taking a [peek](https://github.com/squaremo/amqp.node/blob/main/lib/connection.js#L535-L597) at the amqplib source code, it appears that publish a message eventually calls Buffer.write, and returns the result. So everything looks like it works as I would expect. 

You should however not publish any more messages until the drain event has been emitted, otherwise you risk running out of memory. Then if your application crashes before the inflight messages have been sent, they will be lost. This suggests you may need to apply back pressure to whatever is creating the demand for messages, and that is not always easy to do.
