### ISSUE TITLE
Is there a way to know when a send has completed?

### ISSUE THREAD

**Issue by blackdynamo** [squaremo/amqp.node#95]
I might be missing something but I have not been able to find a way to know when a send is complete. If I am moving messages from one queue to another queue, with some processing in between, I want to know the new message made it to queue 2 before acking the message on queue 1. Is there a way to know when I send a message to queue 2, to know that it has finished sending?

For example:

Promise:

``` javascript
channel
    .sendToQueue(name, message, options)
    .then(function(){
        //ack original queue
    });
```

Callback:

``` javascript
channel.sendToQueue(name, message, options, function(err){
    if(err){
        //handle err
    }
    else{
        //ack original message
    }
});
```

**Comment by Coaxial** [comment]
I'm confused about this. Shouldn't `Channel#sendToQueue` be an async function by default considering it *has* to deal with network IO to reach the RabbitMQ server and enqueue the message?

In the RabbitMQ tutorial (https://github.com/rabbitmq/rabbitmq-tutorials/blob/master/javascript-nodejs/src/send.js), they use a `setTimeout` of 500ms after the `sendToQueue` to close the connection and exit because if you don't do that the script exits before the message is enqueued.

To illustrate, this will print the console.log but won't enqueue the message:

```javascript
#!/usr/bin/env node

var amqp = require('amqplib/callback_api');

amqp.connect('amqp://docker:32771', function(err, conn) {
  if (err) throw err;
  conn.createChannel(function(err, ch) {
    if (err) throw err;
    var q = 'hello';

    ch.assertQueue(q, {durable: false});
    ch.sendToQueue(q, new Buffer('Hello World!'));
    console.log(" [x] Sent 'Hello World!'");

    conn.close();
    process.exit(0);
  });
});
```

If `Channel#sendToQueue` was truly synchronous, the code above wouldn't be a problem (unless I'm missing something).

Considering the function triggers a network IO, why is `Channel#sendToQueue` synchronous? Shouldn't it take a callback and execute this callback once the network IO is done?

**Comment by squaremo** [comment]
> Considering the function triggers a network IO, why is Channel#sendToQueue synchronous? Shouldn't it take a callback and execute this callback once the network IO is done?

It's not synchronous; it returns as soon as the frame has been buffered for sending. In principle, there could be a callback for when the network I/O has "happened", but this is far less useful than knowing, for example, if the message has reached a queue (using ConfirmChannel).

**Comment by Coaxial** [comment]
Why not let it take an optional callback then when you dont need guaranteed delivery but still want to make sure the network call completed?

It feels wrong that the official example on the RabbitMQ website has to resort to a setTimeout considering it's not a best practice.

**Comment by Coaxial** [comment]
However, I feel the doc should mention it at `Channel#sendToQueue`. I'll make a PR to edit the doc so it's harder to miss.

**Comment by SleepWalker** [comment]
Hello from 2025. Just to be clear ConfirmChannel has additional performance penalty which may not be ok for some part of users. This mode adds additional roundtrip and requires rabbitmq server to reply whether it persisted a message.

Ideally `sendToQueue` should have a callback which will be passed directly to `buffer.write()` (actually not buffer but socket write stream). This will solve all the issues
